// lib/core/localization/app_localizations.dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en'), Locale('es'), Locale('fr'), Locale('de'), Locale('it'),
    Locale('pt'), Locale('ru'), Locale('zh'), Locale('ja'), Locale('ko'),
    Locale('ar'), Locale('hi'), Locale('bn'), Locale('tr'), Locale('nl'),
    Locale('pl'), Locale('sv'), Locale('el'), Locale('th'), Locale('vi'),
  ];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  String get _lang => locale.languageCode;

  // ─── Application Branding ──────────────────────────────────────────────────
  String get appTitle {
    return switch (_lang) {
      'es' => 'USA Tiempo: Radar en Vivo',
      'fr' => 'Météo USA: Radar en Direct',
      'de' => 'USA Wetter: Live Radar',
      'it' => 'USA Meteo: Radar Live',
      'pt' => 'USA Tempo: Radar ao Vivo',
      'nl' => 'USA Weer: Live Radar',
      'pl' => 'USA Pogoda: Radar na Żywo',
      'ru' => 'Погода США: Живой Радар',
      'sv' => 'USA Väder: Live Radar',
      'tr' => 'ABD Hava Durumu: Canlı Radar',
      'el' => 'Καιρός ΗΠΑ: Live Ραντάρ',
      'ar' => 'طقس أمريكا: رادار مباشر',
      'zh' => '美国天气：实时雷达',
      'ja' => 'アメリカの天気：ライブレーダー',
      'ko' => '미국 날씨: 실시간 레이더',
      'hi' => 'अमेरिका मौसम: लाइव रडार',
      'bn' => 'যুক্তরাষ্ট্র আবহাওয়া: লাইভ রাডার',
      'th' => 'สภาพอากาศสหรัฐฯ: เรดาร์สด',
      'vi' => 'Thời tiết Mỹ: Radar Trực tiếp',
      _ => 'USA Weather',
    };
  }

  String get appTagline {
    return switch (_lang) {
      'es' => 'Pronóstico Preciso del Tiempo en EE. UU. y Radar en Vivo',
      'fr' => 'Prévisions Météo Précises pour les États-Unis & Radar en Direct',
      'de' => 'Genaue US-Wettervorhersage & Live-Radar',
      'it' => 'Previsioni Meteo USA Accurate & Radar Live',
      'pt' => 'Previsão do Tempo Precisa nos EUA e Radar ao Vivo',
      'nl' => 'Nauwkeurige Amerikaanse Weersverwachting & Live Radar',
      'pl' => 'Dokładna Prognoza Pogody dla USA i Radar na Żywo',
      'ru' => 'Точный Прогноз Погоды в США и Радар в Реальном Времени',
      'sv' => 'Exakt US Väderprognos & Live Radar',
      'tr' => 'Doğru ABD Hava Tahmini ve Canlı Radar',
      'el' => 'Ακριβής Πρόγνωση Καιρού ΗΠΑ & Live Ραντάρ',
      'ar' => 'توقعات طقس أمريكا الدقيقة ورادار مباشر',
      'zh' => '精准美国天气预报与实时雷达',
      'ja' => '正確な全米天気予報とライブ雷雨レーダー',
      'ko' => '정확한 미국 일기예보 및 실시간 레이더',
      'hi' => 'सटीक अमेरिका मौसम पूर्वानुमान और लाइव रडार',
      'bn' => 'সঠিক যুক্তরাষ্ট্র আবহাওয়া পূর্বানুমান ও লাইভ রাডার',
      'th' => 'พยากรณ์อากาศสหรัฐฯ ที่แม่นยำและเรดาร์สด',
      'vi' => 'Dự báo Thời tiết Mỹ Chính xác & Radar Trực tiếp',
      _ => 'Accurate US Weather Forecast & Live Radar',
    };
  }

  // ─── Navigation Tabs ───────────────────────────────────────────────────────
  String get navHome {
    return switch (_lang) {
      'es' => 'Inicio',
      'fr' => 'Accueil',
      'de' => 'Start',
      'it' => 'Home',
      'pt' => 'Início',
      'nl' => 'Start',
      'pl' => 'Główna',
      'ru' => 'Главная',
      'sv' => 'Hem',
      'tr' => 'Ana Sayfa',
      'el' => 'Αρχική',
      'ar' => 'الرئيسية',
      'zh' => '首页',
      'ja' => 'ホーム',
      'ko' => '홈',
      'hi' => 'होम',
      'bn' => 'হোম',
      'th' => 'หน้าแรก',
      'vi' => 'Trang chủ',
      _ => 'Home',
    };
  }

  String get navFavorites {
    return switch (_lang) {
      'es' => 'Favoritos',
      'fr' => 'Favoris',
      'de' => 'Favoriten',
      'it' => 'Preferiti',
      'pt' => 'Favoritos',
      'nl' => 'Favorieten',
      'pl' => 'Ulubione',
      'ru' => 'Избранное',
      'sv' => 'Favoriter',
      'tr' => 'Favoriler',
      'el' => 'Αγαπημένα',
      'ar' => 'المفضلة',
      'zh' => '收藏',
      'ja' => 'お気に入り',
      'ko' => '즐겨찾기',
      'hi' => 'पसंदीदा',
      'bn' => 'পছন্দসই',
      'th' => 'รายการโปรด',
      'vi' => 'Yêu thích',
      _ => 'Favorites',
    };
  }

  String get navCities {
    return switch (_lang) {
      'es' => 'Ciudades',
      'fr' => 'Villes',
      'de' => 'Städte',
      'it' => 'Città',
      'pt' => 'Cidades',
      'nl' => 'Steden',
      'pl' => 'Miasta',
      'ru' => 'Города',
      'sv' => 'Städer',
      'tr' => 'Şehirler',
      'el' => 'Πόλεις',
      'ar' => 'المدن',
      'zh' => '城市',
      'ja' => '都市',
      'ko' => '도시',
      'hi' => 'शहर',
      'bn' => 'শহর',
      'th' => 'เมือง',
      'vi' => 'Thành phố',
      _ => 'Cities',
    };
  }

  String get navRadar {
    return switch (_lang) {
      'ar' => 'الرادار',
      'ru' => 'Радар',
      'zh' => '雷达',
      'ja' => 'レーダー',
      'ko' => '레이더',
      'hi' => 'रडार',
      'bn' => 'রাডার',
      'th' => 'เรดาร์',
      'el' => 'Ραντάρ',
      _ => 'Radar',
    };
  }

  String get navSettings {
    return switch (_lang) {
      'es' => 'Ajustes',
      'fr' => 'Paramètres',
      'de' => 'Einstellungen',
      'it' => 'Impostazioni',
      'pt' => 'Definições',
      'nl' => 'Instellingen',
      'pl' => 'Ustawienia',
      'ru' => 'Настройки',
      'sv' => 'Inställningar',
      'tr' => 'Ayarlar',
      'el' => 'Ρυθμίσεις',
      'ar' => 'الإعدادات',
      'zh' => '设置',
      'ja' => '設定',
      'ko' => '설정',
      'hi' => 'सेटिंग्स',
      'bn' => 'সেটিংস',
      'th' => 'การตั้งค่า',
      'vi' => 'Cài đặt',
      _ => 'Settings',
    };
  }

  // ─── Common Terms ─────────────────────────────────────────────────────────
  String get systemDefault {
    return switch (_lang) {
      'es' => 'Predeterminado del sistema',
      'fr' => 'Par défaut du système',
      'de' => 'Systemstandard',
      'it' => 'Predefinito di sistema',
      'pt' => 'Padrão do sistema',
      'nl' => 'Systeemstandaard',
      'pl' => 'Domyślny systemowy',
      'ru' => 'Системный по умолчанию',
      'sv' => 'Systemstandard',
      'tr' => 'Sistem Varsayılanı',
      'el' => 'Προεπιλογή συστήματος',
      'ar' => 'افتراضي النظام',
      'zh' => '系统默认',
      'ja' => 'システムのデフォルト',
      'ko' => '시스템 기본값',
      'hi' => 'सिस्टम डिफ़ॉल्ट',
      'bn' => 'সিস্টেম ডিফল্ট',
      'th' => 'ค่าเริ่มต้นของระบบ',
      'vi' => 'Mặc định hệ thống',
      _ => 'System Default',
    };
  }

  String get today {
    return switch (_lang) {
      'es' => 'Hoy',
      'fr' => 'Aujourd\'hui',
      'de' => 'Heute',
      'it' => 'Oggi',
      'pt' => 'Hoje',
      'nl' => 'Vandaag',
      'pl' => 'Dzisiaj',
      'ru' => 'Сегодня',
      'sv' => 'Idag',
      'tr' => 'Bugün',
      'el' => 'Σήμερα',
      'ar' => 'اليوم',
      'zh' => '今天',
      'ja' => '今日',
      'ko' => '오늘',
      'hi' => 'आज',
      'bn' => 'আজ',
      'th' => 'วันนี้',
      'vi' => 'Hôm nay',
      _ => 'Today',
    };
  }

  String get now {
    return switch (_lang) {
      'es' => 'Ahora',
      'fr' => 'Maintenant',
      'de' => 'Jetzt',
      'it' => 'Ora',
      'pt' => 'Agora',
      'nl' => 'Nu',
      'pl' => 'Teraz',
      'ru' => 'Сейчас',
      'sv' => 'Nu',
      'tr' => 'Şimdi',
      'el' => 'Τώρα',
      'ar' => 'الآن',
      'zh' => '现在',
      'ja' => '今',
      'ko' => '지금',
      'hi' => 'अब',
      'bn' => 'এখন',
      'th' => 'ตอนนี้',
      'vi' => 'Bây giờ',
      _ => 'Now',
    };
  }

  String get loading {
    return switch (_lang) {
      'es' => 'Cargando información meteorológica...',
      'fr' => 'Chargement des données météo...',
      'de' => 'Wetterdaten werden geladen...',
      'it' => 'Caricamento dati meteo...',
      'pt' => 'A carregar dados meteorológicos...',
      'nl' => 'Weergegevens laden...',
      'pl' => 'Ładowanie danych pogodowych...',
      'ru' => 'Загрузка погоды...',
      'sv' => 'Laddar väderdata...',
      'tr' => 'Hava durumu yükleniyor...',
      'el' => 'Φόρτωση καιρικών δεδομένων...',
      'ar' => 'جاري تحميل بيانات الطقس...',
      'zh' => '正在加载天气数据...',
      'ja' => '天気データを読み込み中...',
      'ko' => '날씨 정보를 불러오는 중...',
      'hi' => 'मौसम डेटा लोड हो रहा है...',
      'bn' => 'আবহাওয়া তথ্য লোড হচ্ছে...',
      'th' => 'กำลังโหลดข้อมูลสภาพอากาศ...',
      'vi' => 'Đang tải dữ liệu thời tiết...',
      _ => 'Loading weather data...',
    };
  }

  String get retry {
    return switch (_lang) {
      'es' => 'Reintentar',
      'fr' => 'Réessayer',
      'de' => 'Wiederholen',
      'it' => 'Riprova',
      'pt' => 'Repetir',
      'nl' => 'Opnieuw proberen',
      'pl' => 'Ponów',
      'ru' => 'Повторить',
      'sv' => 'Försök igen',
      'tr' => 'Tekrar Dene',
      'el' => 'Δοκιμάστε ξανά',
      'ar' => 'إعادة المحاولة',
      'zh' => '重试',
      'ja' => '再試行',
      'ko' => '다시 시도',
      'hi' => 'पुनः प्रयास करें',
      'bn' => 'আবার চেষ্টা করুন',
      'th' => 'ลองใหม่',
      'vi' => 'Thử lại',
      _ => 'Retry',
    };
  }

  // ─── Weather Metric Headers ───────────────────────────────────────────────
  String get sevenDayForecast {
    return switch (_lang) {
      'es' => 'PRONÓSTICO DE 7 DÍAS',
      'fr' => 'PRÉVISIONS SUR 7 JOURS',
      'de' => '7-TAGE-VORHERSAGE',
      'it' => 'PREVISIONI A 7 GIORNI',
      'pt' => 'PREVISÃO DE 7 DIAS',
      'nl' => '7-DAAGSE VERWACHTING',
      'pl' => 'PROGNOZA NA 7 DNI',
      'ru' => 'ПРОГНОЗ НА 7 ДНЕЙ',
      'sv' => '7-DAGARSPROGNOS',
      'tr' => '7 GÜNLÜK HAVA DURUMU',
      'el' => 'ΠΡΟΓΝΩΣΗ 7 ΗΜΕΡΩΝ',
      'ar' => 'توقعات 7 أيام',
      'zh' => '7天天气预报',
      'ja' => '7日間の天気予報',
      'ko' => '7일간의 일기예보',
      'hi' => '7-दिवसीय पूर्वानुमान',
      'bn' => '৭ দিনের পূর্বাভাস',
      'th' => 'พยากรณ์ 7 วัน',
      'vi' => 'DỰ BÁO 7 NGÀY',
      _ => '7-DAY FORECAST',
    };
  }

  String get hourlyForecastTitle {
    return switch (_lang) {
      'es' => 'Pronóstico por horas de este día',
      'fr' => 'Prévisions horaires pour cette journée',
      'de' => 'Stündliche Vorhersage für diesen Tag',
      'it' => 'Previsioni orarie per questo giorno',
      'pt' => 'Previsão horária para este dia',
      'nl' => 'Uurlijkse verwachting voor deze dag',
      'pl' => 'Prognoza godzinowa na ten dzień',
      'ru' => 'Почасовой прогноз на этот день',
      'sv' => 'Timprognos för denna dag',
      'tr' => 'Bu günün saatlik tahmini',
      'el' => 'Ωριαία πρόγνωση για αυτή την ημέρα',
      'ar' => 'التوقعات بالساعة لهذا اليوم',
      'zh' => '本日逐小时预报',
      'ja' => '本日の時間別予報',
      'ko' => '오늘의 시간별 예보',
      'hi' => 'इस दिन का प्रति घंटा पूर्वानुमान',
      'bn' => 'এই দিনের প্রতি ঘণ্টার পূর্বাভাস',
      'th' => 'พยากรณ์รายชั่วโมงสำหรับวันนี้',
      'vi' => 'Dự báo hàng giờ trong ngày',
      _ => 'Hourly forecast for this day',
    };
  }

  String get healthEnvironment {
    return switch (_lang) {
      'es' => 'SALUD Y MEDIO AMBIENTE',
      'fr' => 'SANTÉ ET ENVIRONNEMENT',
      'de' => 'GESUNDHEIT & UMWELT',
      'it' => 'SALUTE E AMBIENTE',
      'pt' => 'SAÚDE E MEIO AMBIENTE',
      'nl' => 'GEZONDHEID & MILIEU',
      'pl' => 'ZDROWIE I ŚRODOWISKO',
      'ru' => 'ЗДОРОВЬЕ И ОКРУЖАЮЩАЯ СРЕДА',
      'sv' => 'HÄLSA & MILJÖ',
      'tr' => 'SAĞLIK VE ÇEVRE',
      'el' => 'ΥΓΕΙΑ ΚΑΙ ΠΕΡΙΒΑΛΛΟΝ',
      'ar' => 'الصحة والبيئة',
      'zh' => '健康与环境',
      'ja' => '健康と環境',
      'ko' => '건강 및 환경',
      'hi' => 'स्वास्थ्य एवं पर्यावरण',
      'bn' => 'স্বাস্থ্য ও পরিবেশ',
      'th' => 'สุขภาพและสิ่งแวดล้อม',
      'vi' => 'SỨC KHỎE & MÔI TRƯỜNG',
      _ => 'HEALTH & ENVIRONMENT',
    };
  }

  String get humidity {
    return switch (_lang) {
      'es' => 'HUMEDAD',
      'fr' => 'HUMIDITÉ',
      'de' => 'LUFTFEUCHTIGKEIT',
      'it' => 'UMIDITÀ',
      'pt' => 'HUMIDADE',
      'nl' => 'LUCHTVOCHTIGHEID',
      'pl' => 'WILGOTNOŚĆ',
      'ru' => 'ВЛАЖНОСТЬ',
      'sv' => 'LUFTFUKTIGHET',
      'tr' => 'NEM',
      'el' => 'ΥΓΡΑΣΙΑ',
      'ar' => 'الرطوبة',
      'zh' => '湿度',
      'ja' => '湿度',
      'ko' => '습도',
      'hi' => 'आर्द्रता',
      'bn' => 'আর্দ্রতা',
      'th' => 'ความชื้น',
      'vi' => 'ĐỘ ẨM',
      _ => 'HUMIDITY',
    };
  }

  String get pressure {
    return switch (_lang) {
      'es' => 'PRESIÓN',
      'fr' => 'PRESSION',
      'de' => 'LUFTDRUCK',
      'it' => 'PRESSIONE',
      'pt' => 'PRESSÃO',
      'nl' => 'LUCHTDRUK',
      'pl' => 'CIŚNIENIE',
      'ru' => 'ДАВЛЕНИЕ',
      'sv' => 'LUFTTRYCK',
      'tr' => 'BASINÇ',
      'el' => 'ΠΙΕΣΗ',
      'ar' => 'الضغط الجوي',
      'zh' => '气压',
      'ja' => '気圧',
      'ko' => '기압',
      'hi' => 'दबाव',
      'bn' => 'বায়ুচাপ',
      'th' => 'ความกดอากาศ',
      'vi' => 'ÁP SUẤT',
      _ => 'PRESSURE',
    };
  }

  String get steady => switch (_lang) {
        'es' => 'Estable',
        'fr' => 'Stable',
        'de' => 'Stabil',
        'it' => 'Stabile',
        'pt' => 'Estável',
        'nl' => 'Stabiel',
        'pl' => 'Stabilne',
        'ru' => 'Стабильно',
        'sv' => 'Stabilt',
        'tr' => 'Sabit',
        'el' => 'Σταθερή',
        'ar' => 'مستقر',
        'zh' => '稳定',
        'ja' => '安定',
        'ko' => '안정',
        'hi' => 'स्थिर',
        'bn' => 'স্থিতিশীল',
        'th' => 'คงที่',
        'vi' => 'Ổn định',
        _ => 'Steady',
      };

  String get uvIndex {
    return switch (_lang) {
      'es' => 'ÍNDICE UV',
      'fr' => 'INDICE UV',
      'de' => 'UV-INDEX',
      'it' => 'INDICE UV',
      'pt' => 'ÍNDICE UV',
      'nl' => 'UV-INDEX',
      'pl' => 'INDEKS UV',
      'ru' => 'УФ-ИНДЕКС',
      'sv' => 'UV-INDEX',
      'tr' => 'UV İNDEKSİ',
      'el' => 'ΔΕΙΚΤΗΣ UV',
      'ar' => 'مؤشر الأشعة',
      'zh' => '紫外线指数',
      'ja' => 'UVインデックス',
      'ko' => '자외선 지수',
      'hi' => 'यूवी सूचकांक',
      'bn' => 'ইউভি সূচক',
      'th' => 'ดัชนี UV',
      'vi' => 'CHỈ SỐ UV',
      _ => 'UV INDEX',
    };
  }

  String get wind {
    return switch (_lang) {
      'es' => 'VIENTO',
      'fr' => 'VENT',
      'de' => 'WIND',
      'it' => 'VENTO',
      'pt' => 'VENTO',
      'nl' => 'WIND',
      'pl' => 'WIATR',
      'ru' => 'ВЕТЕР',
      'sv' => 'VIND',
      'tr' => 'RÜZGAR',
      'el' => 'ΑΝΕΜΟΣ',
      'ar' => 'الرياح',
      'zh' => '风速',
      'ja' => '風速',
      'ko' => '풍속',
      'hi' => 'हवा',
      'bn' => 'বাতাস',
      'th' => 'ลม',
      'vi' => 'GIÓ',
      _ => 'WIND',
    };
  }

  String get windGusts {
    return switch (_lang) {
      'es' => 'Rachas de viento',
      'fr' => 'Rafales de vent',
      'de' => 'Windböen',
      'it' => 'Raffiche di vento',
      'pt' => 'Rajadas de vento',
      'nl' => 'Windstoten',
      'pl' => 'Porywy wiatru',
      'ru' => 'Порывы ветра',
      'sv' => 'Vindbyar',
      'tr' => 'Rüzgar hamleleri',
      'el' => 'Ριπές ανέμου',
      'ar' => 'هبات الرياح',
      'zh' => '阵风',
      'ja' => '突風',
      'ko' => '돌풍',
      'hi' => 'हवा के झोंके',
      'bn' => 'দমকা হাওয়া',
      'th' => 'ลมกระโชก',
      'vi' => 'Gió giật',
      _ => 'Wind Gusts',
    };
  }

  String get visibility {
    return switch (_lang) {
      'es' => 'VISIBILIDAD',
      'fr' => 'VISIBILITÉ',
      'de' => 'SICHTWEITE',
      'it' => 'VISIBILITÀ',
      'pt' => 'VISIBILIDADE',
      'nl' => 'ZICHT',
      'pl' => 'WIDOCZNOŚĆ',
      'ru' => 'ВИДИМОСТЬ',
      'sv' => 'SIKT',
      'tr' => 'GÖRÜŞ MESAFESİ',
      'el' => 'ΟΡΑΤΟΤΗΤΑ',
      'ar' => 'الرؤية الأفقية',
      'zh' => '能见度',
      'ja' => '視程',
      'ko' => '가시거리',
      'hi' => 'दृश्यता',
      'bn' => 'দৃশ্যমানতা',
      'th' => 'ทัศนวิสัย',
      'vi' => 'TẦM NHÌN',
      _ => 'VISIBILITY',
    };
  }

  String get clearVisibility {
    return switch (_lang) {
      'es' => 'Visibilidad clara',
      'fr' => 'Visibilité dégagée',
      'de' => 'Klare Sicht',
      'it' => 'Visibilità limpida',
      'pt' => 'Visibilidade limpa',
      'nl' => 'Helder zicht',
      'pl' => 'Przejrzysta widoczność',
      'ru' => 'Хорошая видимость',
      'sv' => 'God sikt',
      'tr' => 'Açık görüş',
      'el' => 'Καθαρή ορατότητα',
      'ar' => 'رؤية واضحة',
      'zh' => '视线良好',
      'ja' => '視界良好',
      'ko' => '맑은 시야',
      'hi' => 'स्पष्ट दृश्यता',
      'bn' => 'পরিষ্কার দৃশ্যমানতা',
      'th' => 'ทัศนวิสัยแจ่มใส',
      'vi' => 'Tầm nhìn rõ ràng',
      _ => 'Clear visibility',
    };
  }

  String get pollenAllergy {
    return switch (_lang) {
      'es' => 'POLEN Y ALERGIAS',
      'fr' => 'POLLEN ET ALLERGIES',
      'de' => 'POLLEN & ALLERGIE',
      'it' => 'POLLINE E ALLERGIE',
      'pt' => 'PÓLEN E ALERGIAS',
      'nl' => 'POLLEN & ALLERGIE',
      'pl' => 'PYŁKI I ALERGIE',
      'ru' => 'ПЫЛЬЦА И АЛЛЕРГИЯ',
      'sv' => 'POLLEN & ALLERGI',
      'tr' => 'POLEN VE ALERJİ',
      'el' => 'ΓΥΡΗ ΚΑΙ ΑΛΛΕΡΓΙΕΣ',
      'ar' => 'حبوب اللقاح والحساسية',
      'zh' => '花粉与过敏',
      'ja' => '花粉とアレルギー',
      'ko' => '꽃가루 및 알레르기',
      'hi' => 'पराग और एलर्जी',
      'bn' => 'পরাগ ও অ্যালার্জি',
      'th' => 'ละอองเกสรและภูมิแพ้',
      'vi' => 'PHẤN HOA & DỊ ỨNG',
      _ => 'POLLEN & ALLERGY',
    };
  }

  String get pollenTypes {
    return switch (_lang) {
      'es' => 'Árboles, Gramíneas, Malezas',
      'fr' => 'Arbres, Graminées, Herbacées',
      'de' => 'Bäume, Gräser, Unkraut',
      'it' => 'Alberi, Graminacee, Erbe',
      'pt' => 'Árvores, Gramíneas, Ervas',
      'nl' => 'Bomen, Grassen, Onkruid',
      'pl' => 'Drzewa, Trawy, Chwasty',
      'ru' => 'Деревья, Злаки, Сорняки',
      'sv' => 'Träd, Gräs, Ogräs',
      'tr' => 'Ağaç, Çim, Yabani Ot',
      'el' => 'Δέντρα, Αγρωστώδη, Ζιζάνια',
      'ar' => 'أشجار، أعشاب، نباتات برية',
      'zh' => '树木、草类、杂草',
      'ja' => '樹木、イネ科、雑草',
      'ko' => '수목, 잔디, 잡초',
      'hi' => 'पेड़, घास, खरपतवार',
      'bn' => 'গাছ, ঘাস, আগাছা',
      'th' => 'ต้นไม้, หญ้า, วัชพืช',
      'vi' => 'Cây cối, Cỏ, Cỏ dại',
      _ => 'Tree, Grass, Weed Pollen',
    };
  }

  String get clothingSuggestion {
    return switch (_lang) {
      'es' => 'SUGERENCIA DE ROPA',
      'fr' => 'SUGGESTION DE TENUE',
      'de' => 'KLEIDUNGSEMPFEHLUNG',
      'it' => 'CONSIGLIO ABBIGLIAMENTO',
      'pt' => 'SUGESTÃO DE ROUPA',
      'nl' => 'KLEDINGADVIES',
      'pl' => 'SUGESTIA UBIORU',
      'ru' => 'РЕКОМЕНДАЦИЯ В ОДЕЖДЕ',
      'sv' => 'KLÄDFÖRSLAG',
      'tr' => 'KIYAFET ÖNERİSİ',
      'el' => 'ΠΡΟΤΑΣΗ ΕΝΔΥΜΑΣΙΑΣ',
      'ar' => 'اقتراح الملابس',
      'zh' => '穿衣指南',
      'ja' => '服装の提案',
      'ko' => '옷차림 추천',
      'hi' => 'कपड़ों का सुझाव',
      'bn' => 'পোশাকের পরামর্শ',
      'th' => 'คำแนะนำการแต่งกาย',
      'vi' => 'GỢI Ý TRANG PHỤC',
      _ => 'CLOTHING SUGGESTION',
    };
  }

  String get basedOnForecast {
    return switch (_lang) {
      'es' => 'Basado en el pronóstico',
      'fr' => 'Basé sur les prévisions',
      'de' => 'Basierend auf Vorhersage',
      'it' => 'Basato sulle previsioni',
      'pt' => 'Baseado na previsão',
      'nl' => 'Gebaseerd op verwachting',
      'pl' => 'Na podstawie prognozy',
      'ru' => 'На основе прогноза',
      'sv' => 'Baserat på prognosen',
      'tr' => 'Tahmine göre',
      'el' => 'Βάσει πρόγνωσης',
      'ar' => 'بناءً على التوقعات',
      'zh' => '基于天气预报',
      'ja' => '予報に基づく推奨',
      'ko' => '예보 기반 권장',
      'hi' => 'पूर्वानुमान के आधार पर',
      'bn' => 'পূর্বাভাসের ভিত্তিতে',
      'th' => 'อิงตามการพยากรณ์',
      'vi' => 'Dựa trên dự báo thời tiết',
      _ => 'Based on forecast weather',
    };
  }

  String get solarCycle {
    return switch (_lang) {
      'es' => 'CICLO SOLAR',
      'fr' => 'CYCLE SOLAIRE',
      'de' => 'SONNENZYKLUS',
      'it' => 'CICLO SOLARE',
      'pt' => 'CICLO SOLAR',
      'nl' => 'ZONNECYCLUS',
      'pl' => 'CYKL SŁONECZNY',
      'ru' => 'СОЛНЕЧНЫЙ ЦИКЛ',
      'sv' => 'SOLCYKEL',
      'tr' => 'GÜNEŞ DÖNGÜSÜ',
      'el' => 'ΗΛΙΑΚΟΣ ΚΥΚΛΟΣ',
      'ar' => 'دورة الشمس',
      'zh' => '太阳周期',
      'ja' => '太陽サイクル',
      'ko' => '태양 주기',
      'hi' => 'सूर्य चक्र',
      'bn' => 'সূর্য চক্র',
      'th' => 'วงจรดวงอาทิตย์',
      'vi' => 'CHU KỲ MẶT TRỜI',
      _ => 'SOLAR CYCLE',
    };
  }

  String get sunrise {
    return switch (_lang) {
      'es' => 'Amanecer',
      'fr' => 'Lever du soleil',
      'de' => 'Sonnenaufgang',
      'it' => 'Alba',
      'pt' => 'Nascer do sol',
      'nl' => 'Zonsopgang',
      'pl' => 'Wschód słońca',
      'ru' => 'Восход',
      'sv' => 'Soluppgång',
      'tr' => 'Gün doğumu',
      'el' => 'Ανατολή',
      'ar' => 'الشروق',
      'zh' => '日出',
      'ja' => '日の出',
      'ko' => '일출',
      'hi' => 'सूर्योदय',
      'bn' => 'সূর্যোদয়',
      'th' => 'พระอาทิตย์ขึ้น',
      'vi' => 'Bình minh',
      _ => 'Sunrise',
    };
  }

  String get sunset {
    return switch (_lang) {
      'es' => 'Atardecer',
      'fr' => 'Coucher du soleil',
      'de' => 'Sonnenuntergang',
      'it' => 'Tramonto',
      'pt' => 'Pôr do sol',
      'nl' => 'Zonsondergang',
      'pl' => 'Zachód słońca',
      'ru' => 'Закат',
      'sv' => 'Solnedgång',
      'tr' => 'Gün batımı',
      'el' => 'Δύση',
      'ar' => 'الغروب',
      'zh' => '日落',
      'ja' => '日の入り',
      'ko' => '일몰',
      'hi' => 'सूर्यास्त',
      'bn' => 'সূর্যাস্ত',
      'th' => 'พระอาทิตย์ตก',
      'vi' => 'Hoàng hôn',
      _ => 'Sunset',
    };
  }

  String get dayPill => switch (_lang) {
        'es' => 'DÍA',
        'fr' => 'JOUR',
        'de' => 'TAG',
        'it' => 'GIORNO',
        'pt' => 'DIA',
        'nl' => 'DAG',
        'pl' => 'DZIEŃ',
        'ru' => 'ДЕНЬ',
        'sv' => 'DAG',
        'tr' => 'GÜNDÜZ',
        'el' => 'ΗΜΕΡΑ',
        'ar' => 'نهار',
        'zh' => '白天',
        'ja' => '昼',
        'ko' => '낮',
        'hi' => 'दिन',
        'bn' => 'দিন',
        'th' => 'กลางวัน',
        'vi' => 'NGÀY',
        _ => 'DAY',
      };

  String get nightPill => switch (_lang) {
        'es' => 'NOCHE',
        'fr' => 'NUIT',
        'de' => 'NACHT',
        'it' => 'NOTTE',
        'pt' => 'NOITE',
        'nl' => 'NACHT',
        'pl' => 'NOC',
        'ru' => 'НОЧЬ',
        'sv' => 'NATT',
        'tr' => 'GECE',
        'el' => 'ΝΥΧΤΑ',
        'ar' => 'ليل',
        'zh' => '夜间',
        'ja' => '夜',
        'ko' => '밤',
        'hi' => 'रात',
        'bn' => 'রাত',
        'th' => 'กลางคืน',
        'vi' => 'ĐÊM',
        _ => 'NIGHT',
      };

  String get sportOutdoor {
    return switch (_lang) {
      'es' => 'Deporte y Aire Libre',
      'fr' => 'Sport et Plein Air',
      'de' => 'Sport & Outdoor',
      'it' => 'Sport e Tempo Libero',
      'pt' => 'Desporto e Ar Livre',
      'nl' => 'Sport & Buiten',
      'pl' => 'Sport i Rekreacja',
      'ru' => 'Спорт и Активность',
      'sv' => 'Sport & Utomhus',
      'tr' => 'Spor ve Açık Hava',
      'el' => 'Σπορ & Υπαίθριες δραστηριότητες',
      'ar' => 'الرياضة والأنشطة الخارجية',
      'zh' => '运动与户外',
      'ja' => 'スポーツ＆アウトドア',
      'ko' => '스포츠 & 야외활동',
      'hi' => 'खेल और आउटडोर',
      'bn' => 'খেলাধুলা ও আউটডোর',
      'th' => 'กีฬาและกิจกรรมกลางแจ้ง',
      'vi' => 'Thể thao & Hoạt động ngoài trời',
      _ => 'Sport & Outdoor',
    };
  }

  String get running {
    return switch (_lang) {
      'es' => 'Running',
      'fr' => 'Course à pied',
      'de' => 'Laufen',
      'it' => 'Corsa',
      'pt' => 'Corrida',
      'nl' => 'Hardlopen',
      'pl' => 'Bieganie',
      'ru' => 'Бег',
      'sv' => 'Löpning',
      'tr' => 'Koşu',
      'el' => 'Τρέξιμο',
      'ar' => 'الجري',
      'zh' => '跑步',
      'ja' => 'ランニング',
      'ko' => '러닝',
      'hi' => 'दौड़ना',
      'bn' => 'দৌড়ানো',
      'th' => 'วิ่ง',
      'vi' => 'Chạy bộ',
      _ => 'Running',
    };
  }

  String get hiking {
    return switch (_lang) {
      'es' => 'Senderismo',
      'fr' => 'Randonnée',
      'de' => 'Wandern',
      'it' => 'Trekking',
      'pt' => 'Caminhada',
      'nl' => 'Wandelen',
      'pl' => 'Vlepki / Trekking',
      'ru' => 'Хайкинг',
      'sv' => 'Vandring',
      'tr' => 'Doğa Yürüyüşü',
      'el' => 'Πεζοπορία',
      'ar' => 'المشي لمسافات طويلة',
      'zh' => '徒步',
      'ja' => 'ハイキング',
      'ko' => '하이킹',
      'hi' => 'हाइकिंग',
      'bn' => 'হাইকিং',
      'th' => 'เดินป่า',
      'vi' => 'Đi bộ đường dài',
      _ => 'Hiking',
    };
  }

  String get cycling {
    return switch (_lang) {
      'es' => 'Ciclismo',
      'fr' => 'Cyclisme',
      'de' => 'Radsport',
      'it' => 'Ciclismo',
      'pt' => 'Ciclismo',
      'nl' => 'Fietsen',
      'pl' => 'Kolarstwo',
      'ru' => 'Велоспорт',
      'sv' => 'Cykling',
      'tr' => 'Bisiklet',
      'el' => 'Ποδηλασία',
      'ar' => 'ركوب الدراجات',
      'zh' => '骑行',
      'ja' => 'サイクリング',
      'ko' => '사이클링',
      'hi' => 'साइकिल चलाना',
      'bn' => 'সাইকেল চালানো',
      'th' => 'ปั่นจักรยาน',
      'vi' => 'Đạp xe',
      _ => 'Cycling',
    };
  }

  String get surfing {
    return switch (_lang) {
      'es' => 'Surf',
      'fr' => 'Surf',
      'de' => 'Surfen',
      'it' => 'Surf',
      'pt' => 'Surf',
      'nl' => 'Surfen',
      'pl' => 'Surfing',
      'ru' => 'Серфинг',
      'sv' => 'Surfing',
      'tr' => 'Sörf',
      'el' => 'Σερφινγκ',
      'ar' => 'ركوب الأمواج',
      'zh' => '冲浪',
      'ja' => 'サーフィン',
      'ko' => '서핑',
      'hi' => 'सर्फिंग',
      'bn' => 'সার্ফিং',
      'th' => 'โต้คลื่น',
      'vi' => 'Lướt sóng',
      _ => 'Surfing',
    };
  }

  String get skiing {
    return switch (_lang) {
      'es' => 'Esquí',
      'fr' => 'Ski',
      'de' => 'Skifahren',
      'it' => 'Sci',
      'pt' => 'Esqui',
      'nl' => 'Skiën',
      'pl' => 'Narciarstwo',
      'ru' => 'Лыжи',
      'sv' => 'Skidåkning',
      'tr' => 'Kayak',
      'el' => 'Σκι',
      'ar' => 'التزلج',
      'zh' => '滑雪',
      'ja' => 'スキー',
      'ko' => '스키',
      'hi' => 'स्कीइंग',
      'bn' => 'স্কিইং',
      'th' => 'เล่นสกี',
      'vi' => 'Trượt tuyết',
      _ => 'Skiing',
    };
  }

  String get golf {
    return switch (_lang) {
      'es' => 'Golf',
      'fr' => 'Golf',
      'de' => 'Golf',
      'it' => 'Golf',
      'pt' => 'Golfe',
      'nl' => 'Golf',
      'pl' => 'Golf',
      'ru' => 'Гольф',
      'sv' => 'Golf',
      'tr' => 'Golf',
      'el' => 'Γκολφ',
      'ar' => 'الغولف',
      'zh' => '高尔夫',
      'ja' => 'ゴルフ',
      'ko' => '골프',
      'hi' => 'गोल्फ़',
      'bn' => 'গলফ',
      'th' => 'กอล์ฟ',
      'vi' => 'Chơi golf',
      _ => 'Golf',
    };
  }

  String get tennis {
    return switch (_lang) {
      'es' => 'Tenis',
      'fr' => 'Tennis',
      'de' => 'Tennis',
      'it' => 'Tennis',
      'pt' => 'Ténis',
      'nl' => 'Tennis',
      'pl' => 'Tenis',
      'ru' => 'Теннис',
      'sv' => 'Tennis',
      'tr' => 'Tenis',
      'el' => 'Τένις',
      'ar' => 'كرة المضرب',
      'zh' => '网球',
      'ja' => 'テニス',
      'ko' => '테니스',
      'hi' => 'टेनिस',
      'bn' => 'টেনিস',
      'th' => 'เทนนิส',
      'vi' => 'Quần vợt',
      _ => 'Tennis',
    };
  }

  String get runningConditionGood {
    return switch (_lang) {
      'es' => 'Buenas condiciones ahora',
      'fr' => 'Bonnes conditions actuellement',
      'de' => 'Gute Bedingungen jetzt',
      'it' => 'Buone condizioni adesso',
      'pt' => 'Boas condições agora',
      'nl' => 'Goede omstandigheden nu',
      'pl' => 'Dobre warunki teraz',
      'ru' => 'Хорошие условия сейчас',
      'sv' => 'Goda förhållanden nu',
      'tr' => 'Şu an koşullar iyi',
      'el' => 'Καλές συνθήκες τώρα',
      'ar' => 'ظروف جيدة الآن',
      'zh' => '目前环境适宜',
      'ja' => '現在の運動に適した気象',
      'ko' => '현재 운동하기 좋은 날씨',
      'hi' => 'अभी अच्छी स्थिति है',
      'bn' => 'এখন ভালো পরিস্থিতি',
      'th' => 'สภาพอากาศดีในขณะนี้',
      'vi' => 'Điều kiện tốt vào lúc này',
      _ => 'Good conditions now',
    };
  }

  String get highHumidityPill => switch (_lang) {
        'es' => 'Alta humedad 🌫️',
        'fr' => 'Forte humidité 🌫️',
        'de' => 'Hohe Feuchtigkeit 🌫️',
        'it' => 'Alta umidità 🌫️',
        'pt' => 'Alta humidade 🌫️',
        'nl' => 'Hoge luchtvochtigheid 🌫️',
        'pl' => 'Wysoka wilgotność 🌫️',
        'ru' => 'Высокая влажность 🌫️',
        'sv' => 'Hög luftfuktighet 🌫️',
        'tr' => 'Yüksek nem 🌫️',
        'el' => 'Υψηλή υγρασία 🌫️',
        'ar' => 'رطوبة عالية 🌫️',
        'zh' => '湿度偏高 🌫️',
        'ja' => '湿度高め 🌫️',
        'ko' => '높은 습도 🌫️',
        'hi' => 'उच्च आर्द्रता 🌫️',
        'bn' => 'উচ্চ আর্দ্রতা 🌫️',
        'th' => 'ความชื้นสูง 🌫️',
        'vi' => 'Độ ẩm cao 🌫️',
        _ => 'High humidity 🌫️',
      };

  String get feelsLike {
    return switch (_lang) {
      'es' => 'Sensación térmica',
      'fr' => 'Ressenti',
      'de' => 'Gefühlt',
      'it' => 'Percepita',
      'pt' => 'Sensação de',
      'nl' => 'Gevoelstemperatuur',
      'pl' => 'Odczuwalna',
      'ru' => 'Ощущается как',
      'sv' => 'Känns som',
      'tr' => 'Hissedilen',
      'el' => 'Αίσθηση',
      'ar' => 'الحرارة المحسوسة',
      'zh' => '体感温度',
      'ja' => '体感温度',
      'ko' => '체감 온도',
      'hi' => 'महसूस होता है',
      'bn' => 'অনুভূত হচ্ছে',
      'th' => 'รู้สึกเหมือน',
      'vi' => 'Cảm giác như',
      _ => 'Feels like',
    };
  }

  String get rain {
    return switch (_lang) {
      'es' => 'Lluvia',
      'fr' => 'Pluie',
      'de' => 'Regen',
      'it' => 'Pioggia',
      'pt' => 'Chuva',
      'nl' => 'Regen',
      'pl' => 'Deszcz',
      'ru' => 'Дождь',
      'sv' => 'Regn',
      'tr' => 'Yağmur',
      'el' => 'Βροχή',
      'ar' => 'مطر',
      'zh' => '降雨',
      'ja' => '雨',
      'ko' => '강수',
      'hi' => 'बारिश',
      'bn' => 'বৃষ্টি',
      'th' => 'ฝน',
      'vi' => 'Mưa',
      _ => 'Rain',
    };
  }

  String get minTemp {
    return switch (_lang) {
      'es' => 'Mínima',
      'fr' => 'Minimale',
      'de' => 'Tiefstwert',
      'it' => 'Minima',
      'pt' => 'Mínima',
      'nl' => 'Minimum',
      'pl' => 'Minimalna',
      'ru' => 'Минимум',
      'sv' => 'Min',
      'tr' => 'En Düşük',
      'el' => 'Ελάχιστη',
      'ar' => 'الصغرى',
      'zh' => '最低温',
      'ja' => '最低気温',
      'ko' => '최저기온',
      'hi' => 'न्यूनतम',
      'bn' => 'সর্বনিম্ন',
      'th' => 'ต่ำสุด',
      'vi' => 'Thấp nhất',
      _ => 'Min',
    };
  }

  String get maxTemp {
    return switch (_lang) {
      'es' => 'Máxima',
      'fr' => 'Maximale',
      'de' => 'Höchstwert',
      'it' => 'Massima',
      'pt' => 'Máxima',
      'nl' => 'Maximum',
      'pl' => 'Maksymalna',
      'ru' => 'Максимум',
      'sv' => 'Max',
      'tr' => 'En Yüksek',
      'el' => 'Μέγιστη',
      'ar' => 'العظمى',
      'zh' => '最高温',
      'ja' => '最高気温',
      'ko' => '최고기온',
      'hi' => 'अधिकतम',
      'bn' => 'সর্বোচ্চ',
      'th' => 'สูงสุด',
      'vi' => 'Cao nhất',
      _ => 'Max',
    };
  }

  String get searchHint {
    return switch (_lang) {
      'es' => 'E.g.: New York, Los Angeles, Chicago...',
      'fr' => 'Ex : Madrid, Barcelone, Salamanque...',
      'de' => 'Z. B.: New York, Los Angeles, Chicago...',
      'it' => 'Es: Madrid, Barcellona, Salamanca...',
      'pt' => 'Ex: New York, Los Angeles, Chicago...',
      'nl' => 'Bijv.: New York, Los Angeles, Chicago...',
      'pl' => 'Np.: Madryt, Barcelona, Salamanka...',
      'ru' => 'Напр.: Мадрид, Барселона, Саламанка...',
      'sv' => 'T.ex.: New York, Los Angeles, Chicago...',
      'tr' => 'Örn: Madrid, Barselona, Salamanca...',
      'el' => 'Π.χ.: Μαδρίτη, Βαρκελώνη, Σαλαμάνκα...',
      'ar' => 'مثال: مدريد، برشلونة، سالامانكا...',
      'zh' => '例：马德里、巴塞罗那、萨拉曼卡...',
      'ja' => '例：マドリード、バルセロナ、サラマンカ...',
      'ko' => '예: 마드리드, 바르셀로나, 살라망카...',
      'hi' => 'उदा: मैड्रिड, बार्सिलोना, सालामांका...',
      'bn' => 'যেমন: মাদ্রিদ, বার্সেলোনা, সালামানকা...',
      'th' => 'ตัวอย่าง: มาดริด, บาร์เซโลนา, ซาลามังกา...',
      'vi' => 'VD: New York, Los Angeles, Chicago...',
      _ => 'E.g.: New York, Los Angeles, Chicago...',
    };
  }

  // ─── Weather Condition Codes (WMO 0..99) ──────────────────────────────────
  String getWeatherCondition(int code) {
    return switch (code) {
      0 => switch (_lang) {
          'es' => 'Despejado',
          'fr' => 'Ciel dégagé',
          'de' => 'Klarer Himmel',
          'it' => 'Cielo sereno',
          'pt' => 'Céu limpo',
          'nl' => 'Helder',
          'pl' => 'Bezchmurnie',
          'ru' => 'Ясно',
          'sv' => 'Klart',
          'tr' => 'Açık hava',
          'el' => 'Αίθριος ουρανός',
          'ar' => 'سماء صافية',
          'zh' => '晴天',
          'ja' => '快晴',
          'ko' => '맑음',
          'hi' => 'साफ आसमान',
          'bn' => 'পরিষ্কার আকাশ',
          'th' => 'ท้องฟ้าแจ่มใส',
          'vi' => 'Trời quang',
          _ => 'Clear Sky',
        },
      1 => switch (_lang) {
          'es' => 'Mayormente despejado',
          'fr' => 'Ensoleillé / Éclaircies',
          'de' => 'Überwiegend klar',
          'it' => 'Prevalentemente sereno',
          'pt' => 'Predominantemente limpo',
          'nl' => 'Overwegend helder',
          'pl' => 'Prawie bezchmurnie',
          'ru' => 'Преимущественно ясно',
          'sv' => 'Mest klart',
          'tr' => 'Çoğunlukla açık',
          'el' => 'Κυρίως αίθριος',
          'ar' => 'صافٍ غالباً',
          'zh' => '晴间多云',
          'ja' => '晴れ',
          'ko' => '대체로 맑음',
          'hi' => 'अधिकांशतः साफ',
          'bn' => 'বেশিরভাগ সময় পরিষ্কার',
          'th' => 'แจ่มใสเป็นส่วนใหญ่',
          'vi' => 'Hầu như quang đãng',
          _ => 'Mainly Clear',
        },
      2 => switch (_lang) {
          'es' => 'Parcialmente nublado',
          'fr' => 'Partiellement nuageux',
          'de' => 'Teilweise bewölkt',
          'it' => 'Parzialmente nuvoloso',
          'pt' => 'Parcialmente nublado',
          'nl' => 'Gedeeltelijk bewolkt',
          'pl' => 'Częściowo pochmurno',
          'ru' => 'Переменная облачность',
          'sv' => 'Halvklart',
          'tr' => 'Parçalı bulutlu',
          'el' => 'Μερικώς νεφελώδης',
          'ar' => 'غائم جزئياً',
          'zh' => '局部多云',
          'ja' => 'ところにより曇り',
          'ko' => '구름 조금',
          'hi' => 'आंशिक रूप से बादल',
          'bn' => 'আংশিক মেঘলা',
          'th' => 'มีเมฆเป็นบางส่วน',
          'vi' => 'Có mây từng đợt',
          _ => 'Partly Cloudy',
        },
      3 => switch (_lang) {
          'es' => 'Nublado',
          'fr' => 'Couvert',
          'de' => 'Bedeckt',
          'it' => 'Coperto',
          'pt' => 'Encoberto',
          'nl' => 'Geheel bewolkt',
          'pl' => 'Pochmurno',
          'ru' => 'Пасмурно',
          'sv' => 'Mulet',
          'tr' => 'Kapalı',
          'el' => 'Συννεφιασμένος',
          'ar' => 'غائم كلياً',
          'zh' => '阴天',
          'ja' => '曇り',
          'ko' => '흐림',
          'hi' => 'घने बादल',
          'bn' => 'মেঘলা',
          'th' => 'มีเมฆมาก',
          'vi' => 'U ám',
          _ => 'Overcast',
        },
      45 || 48 => switch (_lang) {
          'es' => 'Niebla',
          'fr' => 'Brouillard',
          'de' => 'Nebel',
          'it' => 'Nebbia',
          'pt' => 'Nevoeiro',
          'nl' => 'Mist',
          'pl' => 'Mgła',
          'ru' => 'Туман',
          'sv' => 'Dimma',
          'tr' => 'Sisli',
          'el' => 'Ομίχλη',
          'ar' => 'ضباب',
          'zh' => '有雾',
          'ja' => '霧',
          'ko' => '안개',
          'hi' => 'कोहरा',
          'bn' => 'কুয়াশা',
          'th' => 'หมอก',
          'vi' => 'Sương mù',
          _ => 'Fog',
        },
      51 || 53 || 55 => switch (_lang) {
          'es' => 'Llovizna',
          'fr' => 'Bruine',
          'de' => 'Nieselregen',
          'it' => 'Pioviggine',
          'pt' => 'Chuvisco',
          'nl' => 'Motregen',
          'pl' => 'Mżawka',
          'ru' => 'Морось',
          'sv' => 'Duggregn',
          'tr' => 'Çiseleyen Yağmur',
          'el' => 'Ψιχάλα',
          'ar' => 'رذاذ خفيف',
          'zh' => '毛毛雨',
          'ja' => '霧雨',
          'ko' => '이슬비',
          'hi' => 'बूंदाबांदी',
          'bn' => 'গুঁড়ি গুঁড়ি বৃষ্টি',
          'th' => 'ฝนตกปรอยๆ',
          'vi' => 'Mưa phùn',
          _ => 'Drizzle',
        },
      56 || 57 => switch (_lang) {
          'es' => 'Llovizna helada',
          'fr' => 'Bruine verglaçante',
          'de' => 'Gefrierender Niesel',
          'it' => 'Pioviggine gelata',
          'pt' => 'Chuvisco congelante',
          'nl' => 'Aanvriezende motregen',
          'pl' => 'Marznąca mżawka',
          'ru' => 'Ледяная морось',
          'sv' => 'Underkylt duggregn',
          'tr' => 'Dondurucu Çisenti',
          'el' => 'Παγωμένη ψιχάλα',
          'ar' => 'رذاذ متجمد',
          'zh' => '冻毛毛雨',
          'ja' => '着氷性の霧雨',
          'ko' => '어는 이슬비',
          'hi' => 'बर्फीली बूंदाबांदी',
          'bn' => 'হিমায়িত গুঁড়ি বৃষ্টি',
          'th' => 'ฝนละอองเยือกแข็ง',
          'vi' => 'Mưa phùn đóng băng',
          _ => 'Freezing Drizzle',
        },
      61 => switch (_lang) {
          'es' => 'Lluvia ligera',
          'fr' => 'Pluie faible',
          'de' => 'Leichter Regen',
          'it' => 'Pioggia leggera',
          'pt' => 'Chuva fraca',
          'nl' => 'Lichte regen',
          'pl' => 'Lekki deszcz',
          'ru' => 'Небольшой дождь',
          'sv' => 'Lätt regn',
          'tr' => 'Hafif Yağmur',
          'el' => 'Ελαφριά βροχή',
          'ar' => 'مطر خفيف',
          'zh' => '小雨',
          'ja' => '小雨',
          'ko' => '약한 비',
          'hi' => 'हल्की बारिश',
          'bn' => 'হালকা বৃষ্টি',
          'th' => 'ฝนตกเล็กน้อย',
          'vi' => 'Mưa nhẹ',
          _ => 'Light Rain',
        },
      63 => switch (_lang) {
          'es' => 'Lluvia moderada',
          'fr' => 'Pluie modérée',
          'de' => 'Mäßiger Regen',
          'it' => 'Pioggia moderata',
          'pt' => 'Chuva moderada',
          'nl' => 'Matige regen',
          'pl' => 'Umiarkowany deszcz',
          'ru' => 'Умеренный дождь',
          'sv' => 'Måttligt regn',
          'tr' => 'Orta Şiddetli Yağmur',
          'el' => 'Μέτρια βροχή',
          'ar' => 'مطر معتدل',
          'zh' => '中雨',
          'ja' => '雨',
          'ko' => '보통 비',
          'hi' => 'मध्यम बारिश',
          'bn' => 'মাঝারি বৃষ্টি',
          'th' => 'ฝนตกปานกลาง',
          'vi' => 'Mưa vừa',
          _ => 'Moderate Rain',
        },
      65 => switch (_lang) {
          'es' => 'Lluvia fuerte',
          'fr' => 'Forte pluie',
          'de' => 'Starker Regen',
          'it' => 'Forte pioggia',
          'pt' => 'Chuva forte',
          'nl' => 'Zware regen',
          'pl' => 'Ulewny deszcz',
          'ru' => 'Сильный дождь',
          'sv' => 'Kraftigt regn',
          'tr' => 'Kuvvetli Yağmur',
          'el' => 'Ισχυρή βροχή',
          'ar' => 'مطر غزير',
          'zh' => '大雨 / 暴雨',
          'ja' => '大雨',
          'ko' => '강한 비',
          'hi' => 'भारी बारिश',
          'bn' => 'ভারী বৃষ্টি',
          'th' => 'ฝนตกหนัก',
          'vi' => 'Mưa to',
          _ => 'Heavy Rain',
        },
      66 || 67 => switch (_lang) {
          'es' => 'Lluvia helada',
          'fr' => 'Pluie verglaçante',
          'de' => 'Gefrierender Regen',
          'it' => 'Pioggia gelata',
          'pt' => 'Chuva congelante',
          'nl' => 'Aanvriezende regen',
          'pl' => 'Marznący deszcz',
          'ru' => 'Ледяной дождь',
          'sv' => 'Underkylt regn',
          'tr' => 'Dondurucu Yağmur',
          'el' => 'Παγωμένη βροχή',
          'ar' => 'مطر متجمد',
          'zh' => '冻雨',
          'ja' => '着氷性の雨',
          'ko' => '어는 비',
          'hi' => 'बर्फीली बारिश',
          'bn' => 'হিমায়িত বৃষ্টি',
          'th' => 'ฝนเยือกแข็ง',
          'vi' => 'Mưa băng',
          _ => 'Freezing Rain',
        },
      71 || 73 || 75 => switch (_lang) {
          'es' => 'Nieve',
          'fr' => 'Neige',
          'de' => 'Schnee',
          'it' => 'Neve',
          'pt' => 'Neve',
          'nl' => 'Sneeuw',
          'pl' => 'Śnieg',
          'ru' => 'Снегопад',
          'sv' => 'Snöfall',
          'tr' => 'Kar Yağışı',
          'el' => 'Χιονόπτωση',
          'ar' => 'ثلج',
          'zh' => '降雪',
          'ja' => '雪',
          'ko' => '눈',
          'hi' => 'बर्फबारी',
          'bn' => 'তুষারপাত',
          'th' => 'หิมะ',
          'vi' => 'Tuyết rơi',
          _ => 'Snow',
        },
      77 => switch (_lang) {
          'es' => 'Granos de nieve',
          'fr' => 'Grains de neige',
          'de' => 'Schneegriesel',
          'it' => 'Granelli di neve',
          'pt' => 'Grãos de neve',
          'nl' => 'Sneeuwkorrels',
          'pl' => 'Śnieg ziarnisty',
          'ru' => 'Снежные зерна',
          'sv' => 'Kornsnö',
          'tr' => 'Kar Taneleri',
          'el' => 'Κόκκοι χιονιού',
          'ar' => 'حبيبات الثلج',
          'zh' => '雪粒',
          'ja' => '雪あられ',
          'ko' => '싸락눈',
          'hi' => 'बर्फ के दाने',
          'bn' => 'তুষারকণা',
          'th' => 'เกล็ดหิมะ',
          'vi' => 'Hạt tuyết',
          _ => 'Snow Grains',
        },
      80 || 81 || 82 => switch (_lang) {
          'es' => 'Chubascos de lluvia',
          'fr' => 'Averses de pluie',
          'de' => 'Regenschauer',
          'it' => 'Rovesci di pioggia',
          'pt' => 'Aguaceiros',
          'nl' => 'Regenbuien',
          'pl' => 'Przelotny deszcz',
          'ru' => 'Ливневый дождь',
          'sv' => 'Regnskurar',
          'tr' => 'Sağanak Yağış',
          'el' => 'Μπόρες βροχής',
          'ar' => 'زخات مطر',
          'zh' => '阵雨',
          'ja' => 'にわか雨',
          'ko' => '소나기',
          'hi' => 'तेज़ बौछारें',
          'bn' => 'বৃষ্টির ঝাপটা',
          'th' => 'ฝนซู่',
          'vi' => 'Mưa rào',
          _ => 'Rain Showers',
        },
      85 || 86 => switch (_lang) {
          'es' => 'Chubascos de nieve',
          'fr' => 'Averses de neige',
          'de' => 'Schneeschauer',
          'it' => 'Rovesci di neve',
          'pt' => 'Aguaceiros de neve',
          'nl' => 'Sneeuwbuien',
          'pl' => 'Przelotny śnieg',
          'ru' => 'Снежный заряд',
          'sv' => 'Snöbyar',
          'tr' => 'Kar Sağanağı',
          'el' => 'Μπόρες χιονιού',
          'ar' => 'زخات ثلجية',
          'zh' => '阵雪',
          'ja' => 'にわか雪',
          'ko' => '눈 소나기',
          'hi' => 'बर्फ की बौछारें',
          'bn' => 'তুষারঝড়',
          'th' => 'หิมะตกเป็นช่วงๆ',
          'vi' => 'Mưa tuyết rào',
          _ => 'Snow Showers',
        },
      95 => switch (_lang) {
          'es' => 'Tormenta eléctrica',
          'fr' => 'Orage',
          'de' => 'Gewitter',
          'it' => 'Temporale',
          'pt' => 'Trovoada',
          'nl' => 'Onweer',
          'pl' => 'Burza',
          'ru' => 'Гроза',
          'sv' => 'Åska',
          'tr' => 'Gök Gürültülü Fırtına',
          'el' => 'Καταιγίδα',
          'ar' => 'عاصفة رعدية',
          'zh' => '雷阵雨',
          'ja' => '雷雨',
          'ko' => '뇌우',
          'hi' => 'आंधी-तूफान',
          'bn' => 'বজ্রঝড়',
          'th' => 'พายุฝนฟ้าคะนอง',
          'vi' => 'Dông bão',
          _ => 'Thunderstorm',
        },
      96 || 99 => switch (_lang) {
          'es' => 'Tormenta con granizo',
          'fr' => 'Orage avec grêle',
          'de' => 'Gewitter mit Hagel',
          'it' => 'Temporale con grandine',
          'pt' => 'Trovoada com granizo',
          'nl' => 'Onweer met hagel',
          'pl' => 'Burza z gradem',
          'ru' => 'Гроза с градом',
          'sv' => 'Åska med hagel',
          'tr' => 'Dolu ile Karışık Fırtına',
          'el' => 'Καταιγίδα με χαλάζι',
          'ar' => 'عاصفة رعدية مع بَرَد',
          'zh' => '雷暴伴有冰雹',
          'ja' => '雹を伴う雷雨',
          'ko' => '우박을 동반한 뇌우',
          'hi' => 'ओलों के साथ तूफान',
          'bn' => 'শিলাবৃষ্টিসহ ঝড়',
          'th' => 'พายุลูกเห็บ',
          'vi' => 'Dông kèm mưa đá',
          _ => 'Thunderstorm with Hail',
        },
      _ => switch (_lang) {
          'es' => 'Tiempo variable',
          'fr' => 'Temps variable',
          'de' => 'Wechselhaft',
          'it' => 'Tempo variabile',
          'pt' => 'Tempo variável',
          'nl' => 'Wisselvallig',
          'pl' => 'Zmienna pogoda',
          'ru' => 'Переменная погода',
          'sv' => 'Varierande väder',
          'tr' => 'Değişken hava',
          'el' => 'Μεταβλητός καιρός',
          'ar' => 'طقس متقلب',
          'zh' => '多变天气',
          'ja' => '変わりやすい天気',
          'ko' => '변덕스러운 날씨',
          'hi' => 'परिवर्तनशील मौसम',
          'bn' => 'পরিবর্তনশীল আবহাওয়া',
          'th' => 'สภาพอากาศแปรปรวน',
          'vi' => 'Thời tiết thay đổi',
          _ => 'Variable Weather',
        },
    };
  }

  // ─── Quality & Index Levels ───────────────────────────────────────────────
  String aqiLevel(int index) {
    if (index <= 20) {
      return switch (_lang) {
        'es' => 'Excelente',
        'fr' => 'Excellente',
        'de' => 'Ausgezeichnet',
        'it' => 'Eccellente',
        'pt' => 'Excelente',
        'nl' => 'Uitstekend',
        'pl' => 'Doskonała',
        'ru' => 'Отличное',
        'sv' => 'Utmärkt',
        'tr' => 'Mükemmel',
        'el' => 'Εξαιρετική',
        'ar' => 'ممتاز',
        'zh' => '优',
        'ja' => '極めて良好',
        'ko' => '매우 좋음',
        'hi' => 'उत्कृष्ट',
        'bn' => 'চমৎকার',
        'th' => 'ดีเยี่ยม',
        'vi' => 'Tuyệt vời',
        _ => 'Excellent',
      };
    }
    if (index <= 40) {
      return switch (_lang) {
        'es' => 'Buena',
        'fr' => 'Bonne',
        'de' => 'Gut',
        'it' => 'Buona',
        'pt' => 'Boa',
        'nl' => 'Goed',
        'pl' => 'Dobra',
        'ru' => 'Хорошее',
        'sv' => 'Bra',
        'tr' => 'İyi',
        'el' => 'Καλή',
        'ar' => 'جيد',
        'zh' => '良',
        'ja' => '良好',
        'ko' => '좋음',
        'hi' => 'अच्छा',
        'bn' => 'ভালো',
        'th' => 'ดี',
        'vi' => 'Tốt',
        _ => 'Fair',
      };
    }
    if (index <= 60) {
      return switch (_lang) {
        'es' => 'Moderada',
        'fr' => 'Modérée',
        'de' => 'Mäßig',
        'it' => 'Moderata',
        'pt' => 'Moderada',
        'nl' => 'Matig',
        'pl' => 'Umiarkowana',
        'ru' => 'Умеренное',
        'sv' => 'Måttlig',
        'tr' => 'Orta',
        'el' => 'Μέτρια',
        'ar' => 'معتدل',
        'zh' => '中度',
        'ja' => '普通',
        'ko' => '보통',
        'hi' => 'मध्यम',
        'bn' => 'মাঝারি',
        'th' => 'ปานกลาง',
        'vi' => 'Trung bình',
        _ => 'Moderate',
      };
    }
    if (index <= 80) {
      return switch (_lang) {
        'es' => 'Pobre',
        'fr' => 'Médiocre',
        'de' => 'Schlecht',
        'it' => 'Scarsa',
        'pt' => 'Fraca',
        'nl' => 'Slecht',
        'pl' => 'Zła',
        'ru' => 'Низкое',
        'sv' => 'Dålig',
        'tr' => 'Zayıf',
        'el' => 'Χαμηλή',
        'ar' => 'غير صحي',
        'zh' => '较差',
        'ja' => 'やや不良',
        'ko' => '나쁨',
        'hi' => 'खराब',
        'bn' => 'খারাপ',
        'th' => 'แย่',
        'vi' => 'Kém',
        _ => 'Poor',
      };
    }
    return switch (_lang) {
      'es' => 'Muy pobre',
      'fr' => 'Très mauvaise',
      'de' => 'Sehr schlecht',
      'it' => 'Molto scarsa',
      'pt' => 'Muito fraca',
      'nl' => 'Zeer slecht',
      'pl' => 'Bardzo zła',
      'ru' => 'Очень плохое',
      'sv' => 'Mycket dålig',
      'tr' => 'Çok Kötü',
      'el' => 'Πολύ χαμηλή',
      'ar' => 'سيء جداً',
      'zh' => '极差',
      'ja' => '非常に不良',
      'ko' => '매우 나쁨',
      'hi' => 'बहुत खराब',
      'bn' => 'খুব খারাপ',
      'th' => 'แย่มาก',
      'vi' => 'Rất kém',
      _ => 'Very Poor',
    };
  }

  String uvLevel(double uv) {
    if (uv < 3) return uvLow;
    if (uv < 6) return uvModerate;
    if (uv < 8) return uvHigh;
    if (uv < 11) return uvVeryHigh;
    return uvExtreme;
  }

  String get uvLow => switch (_lang) {
        'es' => 'Bajo',
        'fr' => 'Faible',
        'de' => 'Niedrig',
        'it' => 'Basso',
        'pt' => 'Baixo',
        'nl' => 'Laag',
        'pl' => 'Niski',
        'ru' => 'Низкий',
        'sv' => 'Låg',
        'tr' => 'Düşük',
        'el' => 'Χαμηλός',
        'ar' => 'منخفض',
        'zh' => '低',
        'ja' => '低い',
        'ko' => '낮음',
        'hi' => 'कम',
        'bn' => 'কম',
        'th' => 'ต่ำ',
        'vi' => 'Thấp',
        _ => 'Low',
      };

  String get uvModerate => switch (_lang) {
        'es' => 'Moderado',
        'fr' => 'Modéré',
        'de' => 'Mäßig',
        'it' => 'Moderato',
        'pt' => 'Moderado',
        'nl' => 'Matig',
        'pl' => 'Umiarkowany',
        'ru' => 'Умеренный',
        'sv' => 'Måttlig',
        'tr' => 'Orta',
        'el' => 'Μέτριος',
        'ar' => 'متوسط',
        'zh' => '中等',
        'ja' => '中程度',
        'ko' => '보통',
        'hi' => 'मध्यम',
        'bn' => 'মাঝারি',
        'th' => 'ปานกลาง',
        'vi' => 'Trung bình',
        _ => 'Moderate',
      };

  String get uvHigh => switch (_lang) {
        'es' => 'Alto',
        'fr' => 'Élevé',
        'de' => 'Hoch',
        'it' => 'Alto',
        'pt' => 'Alto',
        'nl' => 'Hoog',
        'pl' => 'Wysoki',
        'ru' => 'Высокий',
        'sv' => 'Hög',
        'tr' => 'Yüksek',
        'el' => 'Υψηλός',
        'ar' => 'مرتفع',
        'zh' => '高',
        'ja' => '高い',
        'ko' => '높음',
        'hi' => 'उच्च',
        'bn' => 'উচ্চ',
        'th' => 'สูง',
        'vi' => 'Cao',
        _ => 'High',
      };

  String get uvVeryHigh => switch (_lang) {
        'es' => 'Muy alto',
        'fr' => 'Très élevé',
        'de' => 'Sehr hoch',
        'it' => 'Molto alto',
        'pt' => 'Muito alto',
        'nl' => 'Zeer hoog',
        'pl' => 'Bardzo wysoki',
        'ru' => 'Очень высокий',
        'sv' => 'Mycket hög',
        'tr' => 'Çok Yüksek',
        'el' => 'Πολύ υψηλός',
        'ar' => 'مرتفع جداً',
        'zh' => '很高',
        'ja' => '非常に高い',
        'ko' => '매우 높음',
        'hi' => 'अत्यधिक',
        'bn' => 'খুব উচ্চ',
        'th' => 'สูงมาก',
        'vi' => 'Rất cao',
        _ => 'Very High',
      };

  String get uvExtreme => switch (_lang) {
        'es' => 'Extremo',
        'fr' => 'Extrême',
        'de' => 'Extrem',
        'it' => 'Estremo',
        'pt' => 'Extremo',
        'nl' => 'Extreem',
        'pl' => 'Ekstremalny',
        'ru' => 'Экстремальный',
        'sv' => 'Extrem',
        'tr' => 'Aşırı',
        'el' => 'Ακραίος',
        'ar' => 'شديد جداً',
        'zh' => '极高',
        'ja' => '危険',
        'ko' => '위험',
        'hi' => 'चरम',
        'bn' => 'চরম',
        'th' => 'อันตราย',
        'vi' => 'Cực kỳ nguy hại',
        _ => 'Extreme',
      };

  String clothingForTemp(double tempC) {
    if (tempC >= 28) {
      return switch (_lang) {
        'es' => 'Camiseta ligera y pantalón corto',
        'fr' => 'T-shirt léger et short',
        'de' => 'Leichtes T-Shirt & Shorts',
        'it' => 'T-shirt leggera e pantaloncini',
        'pt' => 'T-shirt leve e calções',
        'nl' => 'Luchtig T-shirt & korte broek',
        'pl' => 'Lekka koszulka i szorty',
        'ru' => 'Лёгкая футболка и шорты',
        'sv' => 'Lätt t-shirt och shorts',
        'tr' => 'Hafif tişört ve şort',
        'el' => 'Ελαφρύ μπλουζάκι και σορτς',
        'ar' => 'قميص خفيف وشورت',
        'zh' => '清凉短袖与短裤',
        'ja' => '涼しい半袖とショートパンツ',
        'ko' => '시원한 반팔과 반바지',
        'hi' => 'हल्की टी-शर्ट और शॉर्ट्स',
        'bn' => 'হালকা টি-শার্ট ও শর্টস',
        'th' => 'เสื้อยืดแขนสั้นและกางเกงขาสั้น',
        'vi' => 'Áo phông mỏng và quần đùi',
        _ => 'Light Shirt & Shorts',
      };
    }
    if (tempC >= 20) {
      return switch (_lang) {
        'es' => 'Ropa cómoda de verano',
        'fr' => 'Tenue confortable d\'été',
        'de' => 'Bequeme Sommerkleidung',
        'it' => 'Abbigliamento estivo comodo',
        'pt' => 'Roupa confortável de verão',
        'nl' => 'Comfortabele zomerkleding',
        'pl' => 'Wygodny strój letni',
        'ru' => 'Удобная летняя одежда',
        'sv' => 'Bekväma sommarkläder',
        'tr' => 'Rahat yazlık giysiler',
        'el' => 'Άνετα καλοκαιρινά ρούχα',
        'ar' => 'ملابس صيفية مريحة',
        'zh' => '舒适夏装',
        'ja' => '快適な夏服',
        'ko' => '편안한 여름 옷차림',
        'hi' => 'आरामदायक गर्मी के कपड़े',
        'bn' => 'আরামদায়ক গ্রীষ্মের পোশাক',
        'th' => 'เสื้อผ้าฤดูร้อนที่ใส่สบาย',
        'vi' => 'Trang phục mùa hè thoáng mát',
        _ => 'Comfortable Summer Outfit',
      };
    }
    if (tempC >= 14) {
      return switch (_lang) {
        'es' => 'Chaqueta ligera o jersey',
        'fr' => 'Veste légère ou pull',
        'de' => 'Leichte Jacke oder Pullover',
        'it' => 'Giacca leggera o maglione',
        'pt' => 'Casaco leve ou camisola',
        'nl' => 'Lichte jas of trui',
        'pl' => 'Lekka kurtka lub sweter',
        'ru' => 'Лёгкая куртка или свитер',
        'sv' => 'Lätt jacka eller tröja',
        'tr' => 'Hafif ceket veya kazak',
        'el' => 'Ελαφρύ μπουφάν ή πουλόβερ',
        'ar' => 'سترة خفيفة أو كنزة',
        'zh' => '薄外套或长袖卫衣',
        'ja' => '薄手のジャケットやセーター',
        'ko' => '가벼운 겉옷이나 스웨터',
        'hi' => 'हल्की जैकेट या स्वेटर',
        'bn' => 'হালকা জ্যাকেট বা সোয়েটার',
        'th' => 'เสื้อแจ็คเก็ตบางๆ หรือเสื้อกันหนาว',
        'vi' => 'Áo khoác nhẹ hoặc áo len mỏng',
        _ => 'Light Jacket or Sweater',
      };
    }
    return switch (_lang) {
      'es' => 'Abrigo cálido y bufanda',
      'fr' => 'Manteau chaud et écharpe',
      'de' => 'Warmer Mantel & Schal',
      'it' => 'Cappotto caldo e sciarpa',
      'pt' => 'Casaco quente e cachecol',
      'nl' => 'Warme jas en sjaal',
      'pl' => 'Ciepły płaszcz i szal',
      'ru' => 'Тёплое пальто и шарф',
      'sv' => 'Varm jacka och halsduk',
      'tr' => 'Sıcak palto ve atkı',
      'el' => 'Ζεστό παλτό και κασκόλ',
      'ar' => 'معطف دافئ ووشاح',
      'zh' => '保暖大衣与围巾',
      'ja' => '暖かいコートとマフラー',
      'ko' => '따뜻한 코트와 목도리',
      'hi' => 'गर्म कोट और मफलर',
      'bn' => 'উষ্ণ কোট ও স্কার্ফ',
      'th' => 'เสื้อกันหนาวหนาและผ้าพันคอ',
      'vi' => 'Áo khoác ấm và khăn quàng',
      _ => 'Warm Coat & Scarf',
    };
  }

  // ─── Screen: Cities ────────────────────────────────────────────────────────
  String get citiesTitle => switch (_lang) {
        'es' => 'Ciudades de EE. UU.',
        'fr' => 'Villes des États-Unis',
        'de' => 'US-Städte',
        'it' => 'Città degli USA',
        'pt' => 'Cidades dos EUA',
        'nl' => 'Steden van de VS',
        'pl' => 'Miasta USA',
        'ru' => 'Города США',
        'sv' => 'USA-städer',
        'tr' => 'ABD Şehirleri',
        'el' => 'Πόλεις των ΗΠΑ',
        'ar' => 'مدن أمريكا',
        'zh' => '美国城市',
        'ja' => 'アメリカの都市',
        'ko' => '미국 도시',
        'hi' => 'अमेरिका के शहर',
        'bn' => 'যুক্তরাষ্ট্রের শহর',
        'th' => 'เมืองต่างๆ ในสหรัฐฯ',
        'vi' => 'Các thành phố Mỹ',
        _ => 'US Cities',
      };

  String get searchCitiesHint => switch (_lang) {
        'es' => 'Buscar ciudad, provincia o comunidad...',
        'fr' => 'Rechercher ville, province ou région...',
        'de' => 'Stadt, Provinz oder Region suchen...',
        'it' => 'Cerca città, provincia o regione...',
        'pt' => 'Procurar cidade, província ou região...',
        'nl' => 'Zoek stad, provincie of regio...',
        'pl' => 'Szukaj miasta, prowincji lub regionu...',
        'ru' => 'Поиск города, провинции или региона...',
        'sv' => 'Sök stad, provins eller region...',
        'tr' => 'Şehir, il veya bölge ara...',
        'el' => 'Αναζήτηση πόλης, επαρχίας ή περιφέρειας...',
        'ar' => 'البحث عن مدينة أو مقاطعة أو منطقة...',
        'zh' => '搜索城市、省份或自治区...',
        'ja' => '都市、州、地域を検索...',
        'ko' => '도시, 주 또는 지역 검색...',
        'hi' => 'शहर, प्रांत या क्षेत्र खोजें...',
        'bn' => 'শহর, প্রদেশ বা অঞ্চল অনুসন্ধান...',
        'th' => 'ค้นหาเมือง จังหวัด หรือแคว้น...',
        'vi' => 'Tìm thành phố, tỉnh hoặc khu vực...',
        _ => 'Search city, province or region...',
      };

  String get allRegions => switch (_lang) {
        'es' => 'Todas',
        'fr' => 'Toutes',
        'de' => 'Alle',
        'it' => 'Tutte',
        'pt' => 'Todas',
        'nl' => 'Alle',
        'pl' => 'Wszystkie',
        'ru' => 'Все',
        'sv' => 'Alla',
        'tr' => 'Tümü',
        'el' => 'Όλες',
        'ar' => 'الكل',
        'zh' => '全部',
        'ja' => 'すべて',
        'ko' => '전체',
        'hi' => 'सभी',
        'bn' => 'সব',
        'th' => 'ทั้งหมด',
        'vi' => 'Tất cả',
        _ => 'All',
      };

  String get noCitiesFound => switch (_lang) {
        'es' => 'No se encontraron ciudades',
        'fr' => 'Aucune ville trouvée',
        'de' => 'Keine Städte gefunden',
        'it' => 'Nessuna città trovata',
        'pt' => 'Nenhuma cidade encontrada',
        'nl' => 'Geen steden gevonden',
        'pl' => 'Nie znaleziono miast',
        'ru' => 'Города не найдены',
        'sv' => 'Inga städer hittades',
        'tr' => 'Şehir bulunamadı',
        'el' => 'Δεν βρέθηκαν πόλεις',
        'ar' => 'لم يتم العثور على مدن',
        'zh' => '未找到符合条件的城市',
        'ja' => '都市が見つかりません',
        'ko' => '검색된 도시가 없습니다',
        'hi' => 'कोई शहर नहीं मिला',
        'bn' => 'কোনো শহর পাওয়া যায়নি',
        'th' => 'ไม่พบเมือง',
        'vi' => 'Không tìm thấy thành phố nào',
        _ => 'No cities found',
      };

  String get searchCityInUsaTitle => switch (_lang) {
        'es' => 'Buscar ciudad en EE. UU.',
        'fr' => 'Rechercher une ville aux États-Unis',
        'de' => 'Stadt in den USA suchen',
        'it' => 'Cerca una città negli USA',
        'pt' => 'Procurar cidade nos EUA',
        'nl' => 'Zoek stad in de VS',
        'pl' => 'Szukaj miasta w USA',
        'ru' => 'Поиск города в США',
        'sv' => 'Sök stad i USA',
        'tr' => 'ABD\'de Şehir Ara',
        'el' => 'Αναζήτηση πόλης στις ΗΠΑ',
        'ar' => 'البحث عن مدينة في أمريكا',
        'zh' => '搜索美国城市',
        'ja' => 'アメリカの都市を検索',
        'ko' => '미국 도시 검색',
        'hi' => 'अमेरिका में शहर खोजें',
        'bn' => 'যুক্তরাষ্ট্রে শহর অনুসন্ধান করুন',
        'th' => 'ค้นหาเมืองในสหรัฐฯ',
        'vi' => 'Tìm thành phố tại Mỹ',
        _ => 'Search City in USA...',
      };

  String get exploreByRegionHint => switch (_lang) {
        'es' => 'O utiliza la pestaña Ciudades para explorar por regiones',
        'fr' => 'Ou utilisez l\'onglet Villes pour explorer par régions',
        'de' => 'Oder nutzen Sie den Reiter Städte zum Erkunden',
        'it' => 'Oppure usa la scheda Città per esplorare per regione',
        'pt' => 'Ou use o separador Cidades para explorar por região',
        'nl' => 'Of gebruik het tabblad Steden om per regio te zoeken',
        'pl' => 'Lub użyj zakładki Miasta, aby przeglądać regiony',
        'ru' => 'Или используйте вкладку Города для поиска по регионам',
        'sv' => 'Eller använd fliken Städer för att utforska regioner',
        'tr' => 'Veya bölgelere göre aramak için Şehirler sekmesini kullanın',
        'el' => 'Ή χρησιμοποιήστε την καρτέλα Πόλεις για εξερεύνηση',
        'ar' => 'أو استخدم تبويب المدن للاستكشاف حسب المناطق',
        'zh' => '或使用“城市”页面按大区浏览',
        'ja' => 'または「都市」タブから地域別に探せます',
        'ko' => '또는 \'도시\' 탭에서 지역별로 탐색하세요',
        'hi' => 'या क्षेत्रों द्वारा खोजने के लिए शहर टैब का उपयोग करें',
        'bn' => 'অথবা অঞ্চল অনুসারে দেখতে শহর ট্যাব ব্যবহার করুন',
        'th' => 'หรือใช้แท็บเมืองเพื่อดูตามภูมิภาค',
        'vi' => 'Hoặc sử dụng tab Thành phố để khám phá theo khu vực',
        _ => 'Or use the Cities tab to explore by regions',
      };

  // ─── Screen: Favorites ─────────────────────────────────────────────────────
  String get favoritesTitle => switch (_lang) {
        'es' => 'Favoritos',
        'fr' => 'Favoris',
        'de' => 'Favoriten',
        'it' => 'Preferiti',
        'pt' => 'Favoritos',
        'nl' => 'Favorieten',
        'pl' => 'Ulubione',
        'ru' => 'Избранное',
        'sv' => 'Favoriter',
        'tr' => 'Favoriler',
        'el' => 'Αγαπημένα',
        'ar' => 'المفضلة',
        'zh' => '我的收藏',
        'ja' => 'お気に入り',
        'ko' => '즐겨찾기',
        'hi' => 'पसंदीदा',
        'bn' => 'পছন্দসই স্থান',
        'th' => 'รายการโปรด',
        'vi' => 'Danh sách yêu thích',
        _ => 'Favorites',
      };

  String get noFavoritesYet => switch (_lang) {
        'es' => 'Sin favoritos aún',
        'fr' => 'Aucun favori pour le moment',
        'de' => 'Noch keine Favoriten',
        'it' => 'Nessun preferito aggiunto',
        'pt' => 'Sem favoritos ainda',
        'nl' => 'Nog geen favorieten',
        'pl' => 'Brak ulubionych',
        'ru' => 'Нет избранных мест',
        'sv' => 'Inga favoriter än',
        'tr' => 'Henüz favori yok',
        'el' => 'Δεν υπάρχουν ακόμη αγαπημένα',
        'ar' => 'لا توجد مواقع مفضلة بعد',
        'zh' => '暂无收藏城市',
        'ja' => 'お気に入りはまだありません',
        'ko' => '등록된 즐겨찾기가 없습니다',
        'hi' => 'अभी तक कोई पसंदीदा नहीं',
        'bn' => 'এখনো কোনো পছন্দসই স্থান নেই',
        'th' => 'ยังไม่มีรายการโปรด',
        'vi' => 'Chưa có địa điểm yêu thích',
        _ => 'No favorites yet',
      };

  String get tapHeartHint => switch (_lang) {
        'es' => 'Toca ♥ en una ciudad para guardarla',
        'fr' => 'Touchez ♥ sur une ville pour la sauvegarder',
        'de' => 'Tippe auf ♥ bei einer Stadt, um sie zu speichern',
        'it' => 'Tocca ♥ su una città per salvarla',
        'pt' => 'Toque em ♥ numa cidade para guardá-la',
        'nl' => 'Tik op ♥ bij een stad om deze op te slaan',
        'pl' => 'Dotknij ♥ przy mieście, aby je zapisać',
        'ru' => 'Нажмите ♥ на городе, чтобы сохранить его',
        'sv' => 'Tryck på ♥ vid en stad för att spara den',
        'tr' => 'Kaydetmek için bir şehirde ♥ simgesine dokunun',
        'el' => 'Πατήστε ♥ σε μια πόλη για αποθήκευση',
        'ar' => 'اضغط ♥ على أي مدينة لحفظها',
        'zh' => '点击城市上的 ♥ 即可将其保存',
        'ja' => '都市の ♥ をタップして保存できます',
        'ko' => '도시에서 ♥를 눌러 저장하세요',
        'hi' => 'सहेजने के लिए किसी शहर पर ♥ टैप करें',
        'bn' => 'সংরক্ষণ করতে শহরের পাশে ♥ ট্যাপ করুন',
        'th' => 'แตะ ♥ ที่เมืองเพื่อบันทึก',
        'vi' => 'Nhấn ♥ tại một thành phố để lưu lại',
        _ => 'Tap ♥ on a city to save it',
      };

  String get removedFromFavorites => switch (_lang) {
        'es' => 'Eliminado de favoritos',
        'fr' => 'Supprimé des favoris',
        'de' => 'Aus Favoriten entfernt',
        'it' => 'Rimosso dai preferiti',
        'pt' => 'Removido dos favoritos',
        'nl' => 'Verwijderd uit favorieten',
        'pl' => 'Usunięto z ulubionych',
        'ru' => 'Удалено из избранного',
        'sv' => 'Borttagen från favoriter',
        'tr' => 'Favorilerden kaldırıldı',
        'el' => 'Αφαιρέθηκε από τα αγαπημένα',
        'ar' => 'تمت الإزالة من المفضلة',
        'zh' => '已从收藏中移除',
        'ja' => 'お気に入りから削除しました',
        'ko' => '즐겨찾기에서 삭제되었습니다',
        'hi' => 'पसंदीदा से हटा दिया गया',
        'bn' => 'পছন্দসই থেকে সরানো হয়েছে',
        'th' => 'ลบออกจากรายการโปรดแล้ว',
        'vi' => 'Đã xóa khỏi mục yêu thích',
        _ => 'Removed from favorites',
      };

  // ─── Screen: Radar ─────────────────────────────────────────────────────────
  String get radarTitle => switch (_lang) {
        'es' => 'Radar Meteorológico',
        'fr' => 'Radar Météo',
        'de' => 'Wetterradar',
        'it' => 'Radar Meteo',
        'pt' => 'Radar Meteorológico',
        'nl' => 'Weerradar',
        'pl' => 'Radar Pogodowy',
        'ru' => 'Метеорадар',
        'sv' => 'Väderradar',
        'tr' => 'Hava Radarı',
        'el' => 'Ραντάρ Καιρού',
        'ar' => 'رادار الطقس',
        'zh' => '天气雷达',
        'ja' => '気象レーダー',
        'ko' => '기상 레이더',
        'hi' => 'मौसम रडार',
        'bn' => 'আবহাওয়া রাডার',
        'th' => 'เรดาร์สภาพอากาศ',
        'vi' => 'Radar thời tiết',
        _ => 'Weather Radar',
      };

  String get toggleRadarTooltip => switch (_lang) {
        'es' => 'Alternar capa de radar',
        'fr' => 'Activer/Désactiver le radar',
        'de' => 'Radarschicht ein-/ausschalten',
        'it' => 'Attiva/Disattiva radar',
        'pt' => 'Alternar camada de radar',
        'nl' => 'Radar in-/uitschakelen',
        'pl' => 'Włącz/wyłącz radar',
        'ru' => 'Переключить радар',
        'sv' => 'Slå på/av radar',
        'tr' => 'Radarı Aç/Kapat',
        'el' => 'Εναλλαγή ραντάρ',
        'ar' => 'تبديل طبقة الرادار',
        'zh' => '切换雷达图层',
        'ja' => 'レーダーの表示切替',
        'ko' => '레이더 레이어 전환',
        'hi' => 'रडार टॉगल करें',
        'bn' => 'রাডার পরিবর্তন করুন',
        'th' => 'เปิด/ปิดเรดาร์',
        'vi' => 'Bật/tắt lớp radar',
        _ => 'Toggle Radar',
      };

  String get toggleCitiesTooltip => switch (_lang) {
        'es' => 'Mostrar/Ocultar ciudades de EE. UU.',
        'fr' => 'Afficher/Masquer les villes des États-Unis',
        'de' => 'US-Städte ein-/ausblenden',
        'it' => 'Mostra/Nascondi città degli USA',
        'pt' => 'Mostrar/Ocultar cidades dos EUA',
        'nl' => 'Amerikaanse steden tonen/verbergen',
        'pl' => 'Pokaż/ukryj miasta USA',
        'ru' => 'Показать/скрыть города США',
        'sv' => 'Visa/dölj USA-städer',
        'tr' => 'ABD Şehirlerini Göster/Gizle',
        'el' => 'Εμφάνιση/Απόκρυψη πόλεων ΗΠΑ',
        'ar' => 'إظهار/إخفاء مدن أمريكا',
        'zh' => '显示/隐藏美国城市',
        'ja' => 'アメリカの都市の表示/非表示',
        'ko' => '미국 도시 표시/숨기기',
        'hi' => 'अमेरिका के शहरों को दिखाएं/छिपाएं',
        'bn' => 'যুক্তরাষ্ট্রের শহরগুলি প্রদর্শন/লুকান',
        'th' => 'แสดง/ซ่อนเมืองในสหรัฐฯ',
        'vi' => 'Hiện/Ẩn các thành phố Mỹ',
        _ => 'Show/Hide US Cities',
      };

  String get play => switch (_lang) {
        'es' => 'Reproducir',
        'fr' => 'Lecture',
        'de' => 'Abspielen',
        'it' => 'Riproduci',
        'pt' => 'Reproduzir',
        'nl' => 'Afspelen',
        'pl' => 'Odtwórz',
        'ru' => 'Воспроизвести',
        'sv' => 'Spela',
        'tr' => 'Oynat',
        'el' => 'Αναπαραγωγή',
        'ar' => 'تشغيل',
        'zh' => '播放',
        'ja' => '再生',
        'ko' => '재생',
        'hi' => 'चलाएं',
        'bn' => 'চালান',
        'th' => 'เล่น',
        'vi' => 'Phát',
        _ => 'Play',
      };

  String get pause => switch (_lang) {
        'es' => 'Pausar',
        'fr' => 'Pause',
        'de' => 'Pause',
        'it' => 'Pausa',
        'pt' => 'Pausar',
        'nl' => 'Pauze',
        'pl' => 'Pauza',
        'ru' => 'Пауза',
        'sv' => 'Pausa',
        'tr' => 'Duraklat',
        'el' => 'Παύση',
        'ar' => 'إيقاف مؤقت',
        'zh' => '暂停',
        'ja' => '一時停止',
        'ko' => '일시 정지',
        'hi' => 'रोकें',
        'bn' => 'বিরতি',
        'th' => 'หยุดชั่วคราว',
        'vi' => 'Tạm dừng',
        _ => 'Pause',
      };

  String get radarLive => switch (_lang) {
        'es' => 'EN DIRECTO',
        'fr' => 'EN DIRECT',
        'de' => 'LIVE',
        'it' => 'IN DIRETTA',
        'pt' => 'AO VIVO',
        'nl' => 'LIVE',
        'pl' => 'NA ŻYWO',
        'ru' => 'В ПРЯМОМ ЭФИРЕ',
        'sv' => 'DIREKT',
        'tr' => 'CANLI',
        'el' => 'ΖΩΝΤΑΝΑ',
        'ar' => 'مباشر',
        'zh' => '实时',
        'ja' => 'ライブ',
        'ko' => '실시간',
        'hi' => 'लाइव',
        'bn' => 'সরাসরি',
        'th' => 'สด',
        'vi' => 'TRỰC TIẾP',
        _ => 'LIVE',
      };

  String get rainIntensity => switch (_lang) {
        'es' => 'Intensidad de lluvia',
        'fr' => 'Intensité de la pluie',
        'de' => 'Regenintensität',
        'it' => 'Intensità pioggia',
        'pt' => 'Intensidade da chuva',
        'nl' => 'Regenintensiteit',
        'pl' => 'Intensywność opadów',
        'ru' => 'Интенсивность дождя',
        'sv' => 'Regnintensitet',
        'tr' => 'Yağmur Yoğunluğu',
        'el' => 'Ένταση βροχής',
        'ar' => 'شدة المطر',
        'zh' => '降雨强度',
        'ja' => '降雨強度',
        'ko' => '강우 강도',
        'hi' => 'वर्षा की तीव्रता',
        'bn' => 'বৃষ্টির তীব্রতা',
        'th' => 'ความเข้มของฝน',
        'vi' => 'Cường độ mưa',
        _ => 'Rain Intensity',
      };

  String get lightToHeavy => switch (_lang) {
        'es' => 'Ligera → Fuerte',
        'fr' => 'Faible → Forte',
        'de' => 'Leicht → Stark',
        'it' => 'Leggera → Forte',
        'pt' => 'Fraca → Forte',
        'nl' => 'Licht → Zwaar',
        'pl' => 'Lekka → Silna',
        'ru' => 'Слабый → Сильный',
        'sv' => 'Lätt → Kraftig',
        'tr' => 'Hafif → Şiddetli',
        'el' => 'Ελαφριά → Έντονη',
        'ar' => 'خفيف ← غزير',
        'zh' => '小雨 → 大雨',
        'ja' => '弱 → 強',
        'ko' => '약함 → 강함',
        'hi' => 'हल्की → भारी',
        'bn' => 'হালকা → ভারী',
        'th' => 'เบา → หนัก',
        'vi' => 'Nhẹ → Nặng hạt',
        _ => 'Light → Heavy',
      };

  // ─── Screen: Settings ──────────────────────────────────────────────────────
  String get settingsTitle => switch (_lang) {
        'es' => 'Ajustes',
        'fr' => 'Paramètres',
        'de' => 'Einstellungen',
        'it' => 'Impostazioni',
        'pt' => 'Definições',
        'nl' => 'Instellingen',
        'pl' => 'Ustawienia',
        'ru' => 'Настройки',
        'sv' => 'Inställningar',
        'tr' => 'Ayarlar',
        'el' => 'Ρυθμίσεις',
        'ar' => 'الإعدادات',
        'zh' => '设置',
        'ja' => '設定',
        'ko' => '설정',
        'hi' => 'सेटिंग्स',
        'bn' => 'সেটিংস',
        'th' => 'การตั้งค่า',
        'vi' => 'Cài đặt',
        _ => 'Settings',
      };

  String get sectionDisplay => switch (_lang) {
        'es' => 'Pantalla',
        'fr' => 'Affichage',
        'de' => 'Anzeige',
        'it' => 'Visualizzazione',
        'pt' => 'Ecrã',
        'nl' => 'Weergave',
        'pl' => 'Ekran',
        'ru' => 'Отображение',
        'sv' => 'Visning',
        'tr' => 'Görünüm',
        'el' => 'Εμφάνιση',
        'ar' => 'الشاشة',
        'zh' => '外观与显示',
        'ja' => '表示設定',
        'ko' => '화면 설정',
        'hi' => 'प्रदर्शन',
        'bn' => 'প্রদর্শন',
        'th' => 'การแสดงผล',
        'vi' => 'Hiển thị',
        _ => 'Display',
      };

  String get darkMode => switch (_lang) {
        'es' => 'Modo Oscuro',
        'fr' => 'Mode Sombre',
        'de' => 'Dunkelmodus',
        'it' => 'Modalità Scura',
        'pt' => 'Modo Escuro',
        'nl' => 'Donkere modus',
        'pl' => 'Tryb ciemny',
        'ru' => 'Тёмная тема',
        'sv' => 'Mörkt läge',
        'tr' => 'Karanlık Mod',
        'el' => 'Σκοτεινή λειτουργία',
        'ar' => 'الوضع الداكن',
        'zh' => '深色模式',
        'ja' => 'ダークモード',
        'ko' => '다크 모드',
        'hi' => 'डार्क मोड',
        'bn' => 'ডার্ক মোড',
        'th' => 'โหมดมืด',
        'vi' => 'Chế độ tối',
        _ => 'Dark Mode',
      };

  String get useDarkTheme => switch (_lang) {
        'es' => 'Usar tema oscuro',
        'fr' => 'Utiliser le thème sombre',
        'de' => 'Dunkles Design verwenden',
        'it' => 'Usa tema scuro',
        'pt' => 'Utilizar tema escuro',
        'nl' => 'Gebruik donker thema',
        'pl' => 'Używaj ciemnego motywu',
        'ru' => 'Использовать тёмную тему',
        'sv' => 'Använd mörkt tema',
        'tr' => 'Karanlık temayı kullan',
        'el' => 'Χρήση σκούρου θέματος',
        'ar' => 'استخدام السمة الداكنة',
        'zh' => '使用深色高对比度主题',
        'ja' => 'ダークテーマを使用',
        'ko' => '다크 테마 적용',
        'hi' => 'डार्क थीम का उपयोग करें',
        'bn' => 'ডার্ক থিম ব্যবহার করুন',
        'th' => 'ใช้ธีมสีเข้ม',
        'vi' => 'Sử dụng giao diện tối',
        _ => 'Use dark theme',
      };

  String get sectionUnits => switch (_lang) {
        'es' => 'Unidades',
        'fr' => 'Unités',
        'de' => 'Einheiten',
        'it' => 'Unità',
        'pt' => 'Unidades',
        'nl' => 'Eenheden',
        'pl' => 'Jednostki',
        'ru' => 'Единицы измерения',
        'sv' => 'Enheter',
        'tr' => 'Birimler',
        'el' => 'Μονάδες',
        'ar' => 'الوحدات',
        'zh' => '单位制',
        'ja' => '単位',
        'ko' => '단위',
        'hi' => 'इकाइयाँ',
        'bn' => 'একক',
        'th' => 'หน่วยวัด',
        'vi' => 'Đơn vị',
        _ => 'Units',
      };

  String get temperatureUnit => switch (_lang) {
        'es' => 'Temperatura',
        'fr' => 'Température',
        'de' => 'Temperatur',
        'it' => 'Temperatura',
        'pt' => 'Temperatura',
        'nl' => 'Temperatuur',
        'pl' => 'Temperatura',
        'ru' => 'Температура',
        'sv' => 'Temperatur',
        'tr' => 'Sıcaklık',
        'el' => 'Θερμοκρασία',
        'ar' => 'درجة الحرارة',
        'zh' => '温度单位',
        'ja' => '温度単位',
        'ko' => '온도 단위',
        'hi' => 'तापमान इकाई',
        'bn' => 'তাপমাত্রা একক',
        'th' => 'หน่วยอุณหภูมิ',
        'vi' => 'Đơn vị nhiệt độ',
        _ => 'Temperature',
      };

  String get pressureUnit => switch (_lang) {
        'es' => 'Unidad de Presión',
        'fr' => 'Unité de Pression',
        'de' => 'Luftdruckeinheit',
        'it' => 'Unità di Pressione',
        'pt' => 'Unidade de Pressão',
        'nl' => 'Drukeenheid',
        'pl' => 'Jednostka ciśnienia',
        'ru' => 'Единица давления',
        'sv' => 'Lufttrycksenhet',
        'tr' => 'Basınç Birimi',
        'el' => 'Μονάδα Πίεσης',
        'ar' => 'وحدة الضغط',
        'zh' => '气压单位',
        'ja' => '気圧単位',
        'ko' => '기압 단위',
        'hi' => 'दबाव इकाई',
        'bn' => 'চাপের একক',
        'th' => 'หน่วยความกดอากาศ',
        'vi' => 'Đơn vị áp suất',
        _ => 'Pressure Unit',
      };

  String get sectionLanguage => switch (_lang) {
        'es' => 'Idioma',
        'fr' => 'Langue',
        'de' => 'Sprache',
        'it' => 'Lingua',
        'pt' => 'Idioma',
        'nl' => 'Taal',
        'pl' => 'Język',
        'ru' => 'Язык',
        'sv' => 'Språk',
        'tr' => 'Dil',
        'el' => 'Γλώσσα',
        'ar' => 'اللغة',
        'zh' => '语言',
        'ja' => '言語',
        'ko' => '언어',
        'hi' => 'भाषा',
        'bn' => 'ভাষা',
        'th' => 'ภาษา',
        'vi' => 'Ngôn ngữ',
        _ => 'Language',
      };

  String get appLanguage => switch (_lang) {
        'es' => 'Idioma de la aplicación',
        'fr' => 'Langue de l\'application',
        'de' => 'App-Sprache',
        'it' => 'Lingua dell\'app',
        'pt' => 'Idioma da aplicação',
        'nl' => 'App-taal',
        'pl' => 'Język aplikacji',
        'ru' => 'Язык приложения',
        'sv' => 'App-språk',
        'tr' => 'Uygulama Dili',
        'el' => 'Γλώσσα εφαρμογής',
        'ar' => 'لغة التطبيق',
        'zh' => '应用语言',
        'ja' => 'アプリの言語',
        'ko' => '앱 언어',
        'hi' => 'ऐप भाषा',
        'bn' => 'অ্যাপের ভাষা',
        'th' => 'ภาษาของแอป',
        'vi' => 'Ngôn ngữ ứng dụng',
        _ => 'App Language',
      };

  String get selectLanguage => switch (_lang) {
        'es' => 'Seleccionar Idioma',
        'fr' => 'Sélectionner la langue',
        'de' => 'Sprache wählen',
        'it' => 'Seleziona lingua',
        'pt' => 'Selecionar idioma',
        'nl' => 'Kies taal',
        'pl' => 'Wybierz język',
        'ru' => 'Выберите язык',
        'sv' => 'Välj språk',
        'tr' => 'Dil Seçin',
        'el' => 'Επιλογή γλώσσας',
        'ar' => 'اختر اللغة',
        'zh' => '选择语言',
        'ja' => '言語を選択',
        'ko' => '언어 선택',
        'hi' => 'भाषा चुनें',
        'bn' => 'ভাষা নির্বাচন করুন',
        'th' => 'เลือกภาษา',
        'vi' => 'Chọn ngôn ngữ',
        _ => 'Select Language',
      };

  String get sectionAbout => switch (_lang) {
        'es' => 'Acerca de',
        'fr' => 'À propos',
        'de' => 'Über',
        'it' => 'Informazioni',
        'pt' => 'Sobre',
        'nl' => 'Over',
        'pl' => 'O aplikacji',
        'ru' => 'О приложении',
        'sv' => 'Om appen',
        'tr' => 'Hakkında',
        'el' => 'Σχετικά',
        'ar' => 'حول',
        'zh' => '关于',
        'ja' => 'アプリ情報',
        'ko' => '앱 정보',
        'hi' => 'के बारे में',
        'bn' => 'সম্পর্কে',
        'th' => 'เกี่ยวกับ',
        'vi' => 'Thông tin',
        _ => 'About',
      };

  String get version => switch (_lang) {
        'es' => 'Versión',
        'fr' => 'Version',
        'de' => 'Version',
        'it' => 'Versione',
        'pt' => 'Versão',
        'nl' => 'Versie',
        'pl' => 'Wersja',
        'ru' => 'Версия',
        'sv' => 'Version',
        'tr' => 'Sürüm',
        'el' => 'Έκδοση',
        'ar' => 'الإصدار',
        'zh' => '版本',
        'ja' => 'バージョン',
        'ko' => '버전',
        'hi' => 'संस्करण',
        'bn' => 'সংস্করণ',
        'th' => 'เวอร์ชัน',
        'vi' => 'Phiên bản',
        _ => 'Version',
      };

  String get privacyPolicy => switch (_lang) {
        'es' => 'Política de Privacidad',
        'fr' => 'Politique de Confidentialité',
        'de' => 'Datenschutzrichtlinie',
        'it' => 'Informativa sulla Privacy',
        'pt' => 'Política de Privacidade',
        'nl' => 'Privacybeleid',
        'pl' => 'Polityka prywatności',
        'ru' => 'Политика конфиденциальности',
        'sv' => 'Integritetspolicy',
        'tr' => 'Gizlilik Politikası',
        'el' => 'Πολιτική Απορρήτου',
        'ar' => 'سياسة الخصوصية',
        'zh' => '隐私政策',
        'ja' => 'プライバシーポリシー',
        'ko' => '개인정보 처리방침',
        'hi' => 'गोपनीयता नीति',
        'bn' => 'গোপনীয়তা নীতি',
        'th' => 'นโยบายความเป็นส่วนตัว',
        'vi' => 'Chính sách bảo mật',
        _ => 'Privacy Policy',
      };

  String get rateApp => switch (_lang) {
        'es' => 'Calificar la aplicación',
        'fr' => 'Évaluer l\'application',
        'de' => 'App bewerten',
        'it' => 'Valuta l\'app',
        'pt' => 'Avaliar a aplicação',
        'nl' => 'Beoordeel de app',
        'pl' => 'Oceń aplikację',
        'ru' => 'Оценить приложение',
        'sv' => 'Betygsätt appen',
        'tr' => 'Uygulamayı Oyla',
        'el' => 'Αξιολογήστε την εφαρμογή',
        'ar' => 'تقييم التطبيق',
        'zh' => '为我们评分',
        'ja' => 'アプリを評価する',
        'ko' => '앱 평가하기',
        'hi' => 'ऐप को रेट करें',
        'bn' => 'অ্যাপটি রেট করুন',
        'th' => 'ให้คะแนนแอป',
        'vi' => 'Đánh giá ứng dụng',
        _ => 'Rate App',
      };

  String get widgetsTitle => switch (_lang) {
        'es' => 'Secciones de Inicio',
        'fr' => 'Sections de l\'accueil',
        'de' => 'Startseiten-Bereiche',
        'it' => 'Sezioni della Home',
        'pt' => 'Secções do Início',
        'nl' => 'Startpagina secties',
        'pl' => 'Sekcje strony głównej',
        'ru' => 'Разделы главной',
        'sv' => 'Hem-sektioner',
        'tr' => 'Ana Sayfa Bölümleri',
        'el' => 'Ενότητες Αρχικής',
        'ar' => 'أقسام الصفحة الرئيسية',
        'zh' => '首页模块管理',
        'ja' => 'ホーム画面セクション',
        'ko' => '홈 화면 섹션 관리',
        'hi' => 'होम स्क्रीन अनुभाग',
        'bn' => 'হোম স্ক্রিন বিভাগ',
        'th' => 'ส่วนหน้าแรก',
        'vi' => 'Các phần trang chủ',
        _ => 'Home Sections',
      };

  String get customizeHomeSections => switch (_lang) {
        'es' => 'Personalizar secciones visibles',
        'fr' => 'Personnaliser les sections visibles',
        'de' => 'Sichtbare Abschnitte anpassen',
        'it' => 'Personalizza sezioni visibili',
        'pt' => 'Personalizar secções visíveis',
        'nl' => 'Zichtbare secties aanpassen',
        'pl' => 'Dostosuj widoczne sekcje',
        'ru' => 'Настроить видимые разделы',
        'sv' => 'Anpassa synliga sektioner',
        'tr' => 'Görünür bölümleri özelleştir',
        'el' => 'Προσαρμογή ορατών ενοτήτων',
        'ar' => 'تخصيص الأقسام المرئية',
        'zh' => '自定义首页可见模块',
        'ja' => '表示するセクションをカスタマイズ',
        'ko' => '표시할 섹션 맞춤설정',
        'hi' => 'दृश्य अनुभागों को अनुकूलित करें',
        'bn' => 'দৃশ্যমান বিভাগ কাস্টমাইজ করুন',
        'th' => 'ปรับแต่งส่วนที่แสดง',
        'vi' => 'Tùy chỉnh các phần hiển thị',
        _ => 'Customize visible sections',
      };

  String get dayDetails => switch (_lang) {
        'es' => 'Detalles del Día',
        'fr' => 'Détails du Jour',
        'de' => 'Tagesdetails',
        'it' => 'Dettagli del Giorno',
        'pt' => 'Detalhes do Dia',
        'nl' => 'Dagdetails',
        'pl' => 'Szczegóły Dnia',
        'ru' => 'Детали дня',
        'sv' => 'Detaljer för dagen',
        'tr' => 'Günün Detayları',
        'el' => 'Λεπτομέρειες Ημέρας',
        'ar' => 'تفاصيل اليوم',
        'zh' => '当日详情',
        'ja' => '一日の詳細',
        'ko' => '상세 날씨',
        'hi' => 'दिन का विवरण',
        'bn' => 'দিনের বিস্তারিত',
        'th' => 'รายละเอียดของวัน',
        'vi' => 'Chi tiết trong ngày',
        _ => 'Day Details',
      };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
